### ISSUE TITLE
Remote Control API

### ISSUE THREAD

**Issue by jldupont** [rdio/api#1]
Use case:  user opens a desktop browser tab on rdio.com.  User uses his/her Android device to remotely control the desktop browser instance of rdio.

**Comment by iangilman** [comment]
Interesting. The tech I'm working on that should support this is the new JavaScript API. I don't know that we have plans for something like this built into our native SDKs. That said, one could still accomplish this from native via an embedded web panel using the new JS API, even if that's not ideal.

**Comment by jldupont** [comment]
Actually, my first use of this API would be to build a "media keys" bridge to control Rdio from the keyboard... without having to point any mouse pointer at the web browser window.  So annoying.

**Comment by iangilman** [comment]
Interesting. Any reason you're not using the desktop app? What OS are you on?

**Comment by jldupont** [comment]
I use Linux Ubuntu 12.04. 
I have already done a bridge using websockets some time ago but it stopped working with the newer version of the standard.  The bridge relied on directly interacting with rdio buttons in the DOM... I'd like to stay clear of this time around.

**Comment by iangilman** [comment]
We've actually got support for Unity Web Apps... with the beta installed: 

http://www.omgubuntu.co.uk/2012/07/how-to-install-ubuntus-new-web-apps-feature

... your media keys should work with Rdio.

**Comment by jldupont** [comment]
This appears to require Unity... which I don't want to be using.  Also, I suspect Rdio.com will be updated in a more timely fashion than any desktop app.  

Furthermore, the appeal of the API also revolves around the possibility to integrate multiple radio/music applications on the desktop e.g. have mediakeys control, contextually, playback amongst several different services.

**Comment by iangilman** [comment]
I hear you. Well, once we have this API feature together, you should be able to make it happen, as long as you don't mind doing it via JavaScript.

**Comment by jldupont** [comment]
Maybe through Web Messaging, please?
http://www.w3.org/TR/webmessaging/

**Comment by iangilman** [comment]
Our API uses Web Messaging internally, but we're not exposing the protocol directly.

**Comment by srmerritt** [comment]
"Also, I suspect Rdio.com will be updated in a more timely fashion than any desktop app."
FWIW, the desktop app is a thin layer on top of webkit (embedded chromium for windows), so the usual fears of slow desktop app release cycles don't apply.

**Comment by iangilman** [comment]
Of possible interest to this thread: http://src.ianloic.com/linux-rdio

**Comment by jldupont** [comment]
Any ETA on this?  Been 3 months now...

**Comment by rknLA** [comment]
I can't give you an ETA for bringing this into the public API, but the most recent iPhone and Android versions of our Mobile App support this feature.

**Comment by iangilman** [comment]
This has been waiting behind our implementing OAuth 2 scopes (since sharing playstate is going to be something you'll need to specifically opt into), but that's now coming together.

**Comment by iangilman** [comment]
And now it's ready! It works only with the beta JavaScript API... let me know your Rdio username if you want to sign up for it.

Basically with the JS API you can flag your app to share playstate with the rest of the Rdio system, so you can see and control what's being played on the desktop, mobile, and web versions of Rdio.

Also worth noting, as @rknLA pointed out above, is that our mobile apps (but not our mobile SDKs) now also can be used to remote control the desktop and web versions of Rdio (which was not the case when this thread started).
