### ISSUE TITLE
track plays 30 sec clip for premium user in iOS

### ISSUE THREAD

**Issue by Pavan96** [rdio/api#101]
Hi,
    I have implemented rdio api in my application. I have premium account on rdio.
 When I login and play the song it plays song fully. After 15-20 minutes when app goes background (its killed by os ) and I open the app and play the then it plays only 30 seconds. I think its due in background app killed by OS after that session of authorisation is overed because of that it plays 30 sec. track . I am not sure but may be this reason.Any help will be appreciated ?

If I logout and login back then it plays full song. Any help will be appreciated.

**Comment by rknLA** [comment]
Hi @Pavan96,

It sounds like this is related to #102 and resuming the user's session.  Is that correct?

If not, can you provide a sample app that exhibits this problem with some comments about how we can reproduce it?

Thanks!
