### ISSUE TITLE
iOS application Session expired ...Need to login again to play full song .

### ISSUE THREAD

**Issue by Pavan96** [rdio/api#102]
I have integrated rdio api in my application. I have start looking into rdio example ( https://github.com/rdio/hello-ios-playback ) provided in documentation but unable to find a method to maintain session in it.
Please help me to know how I can save my session.

**Comment by rknLA** [comment]
Hi @Pavan96,

I'll file an internal task to update our documentation on this, but the gist of what you'll want to do is store the access token returned by [`-rdioDidAuthorizeUser:withAccessToken:`](https://github.com/rdio/hello-ios-playback/blob/master/Classes/HelloViewController.m#L134-L137) in a secure way (I think the current best practice is to encrypt the token and use the Keychain).

Then, when the app launches, if you have an access token stored, you can call [`-authorizeUsingAccessToken:`](http://www.rdio.com/media/static/developer/ios/docs/interface_rdio.html#a23ef06b9d8244c94c74eadde2fbb2ca4) to authenticate the user without require any user interaction.

**Comment by Pavan96** [comment]
Hi rknLA,
Thanks for your reply. It worked for me I just stored the access token  and re authenticate it. But I think it should be like once you authenticate you should not need again authentication.

**Comment by Pavan96** [comment]
hi,
When I reauthorize using [[AppDelegate rdioInstance] authorizeUsingAccessToken:savedToken fromController:controller in applicationDidBecomeActive then it will call all methods of that view controller like viewWillAppear and all. How I should avoid that ?

**Comment by dasevilla** [comment]
@Pavan96 you should use `authorizeUsingAccessToken:` instead of `authorizeUsingAccessToken:fromController:`. The difference is that the first method will not trigger the modal login if the access token is invalid and will not present any UI to the user. If the access token is invalid you can catch that by handling the `rdioAuthorizationFailed:` of `RdioDelegate`.

**Comment by Pavan96** [comment]
Hi dasevilla ,
I am facing same problem as you told I used above method, But it still moves to my first tab when I call above method in application BecomeaActive.
