### ISSUE TITLE
Search Query no longer returning Track objects in certain circumstances.

### ISSUE THREAD

**Issue by jonreiling** [rdio/api#103]
Up until a few days ago, searching for "rolling stones" would return a mix of artist, album and track objects. Now it just returns artists and albums, with no tracks.

Example in console:
http://rdioconsole.appspot.com/#query%3Drolling%2Bstones%26types%3DArtist%252CAlbum%252CTrack%26method%3Dsearch

Is this a formal change to the API or is there a way to return to having a proper mix of results?

**Comment by dasevilla** [comment]
This appears to be an unintended side-effect of a change we made. The team is looking into this issue.

**Comment by dasevilla** [comment]
Update: we're still working on the best way to increase the track rankings so they match their popularity. The previous method will no longer work.

**Comment by dasevilla** [comment]
Search now returns better results. The issue was that play counts were not affecting the ranking of tracks. This caused tribute/covers albums to rank higher than the original tracks. The team is continuing to improve the quality of search results, but your experience should be much better now.
