### ISSUE TITLE
Search returning irrelevant results

### ISSUE THREAD

**Issue by sastraxi** [rdio/api#104]
Hi there,

Starting this morning (and using the Java API) I'm unable to find a bunch of popular songs through the search. I can navigate to them directly, but cover versions/"feat" artists are being listed above the real ones, and songs can't be found.

Furthermore, the same issues appear through the rdio.com search bar. For example:

http://www.rdio.com/search/arcade%20fire%20rococo/tracks/

Does not show any results, but the track is in my collection:

http://www.rdio.com/artist/Arcade_Fire/album/The_Suburbs_1/track/Rococo/

Thanks!

![rdio-search-unexpected](https://f.cloud.github.com/assets/898348/1633570/49995622-578b-11e3-8a88-d53db13d87a3.png)

**Comment by BronzePointKrel** [comment]
I'm finding this very frustrating as well. Using both the API and the main site search is returning close to zero results. Try search for "the black keys" and the results are cover bands and playlists.

**Comment by sastraxi** [comment]
Search looks like it's back to normal now. How about for you, Ryan?

**Comment by BronzePointKrel** [comment]
It was briefly but has just returned back to it's weird state. For example
1. search for: tighten up black keys
2. search for: smells like teen spirit nirvana

both results (via api and website) are again returning tribute and cover bands instead of the actual proper songs/albums.

frustrating.

**Comment by BronzePointKrel** [comment]
![search](https://f.cloud.github.com/assets/137759/1635543/403b4772-57b1-11e3-9e2f-247ce3fb1110.png)

**Comment by BronzePointKrel** [comment]
Sorry to hijack this ticket but I'm hoping that support can respond to the recent changes to 'search' both in the API and the rdio website. I've included some screenshots of searching for the current #1 pop song, Wake Me Up by Avicii. This was picked as an example of something that is probably being searched for frequently.

Example 1: The track is found when using the API and not authenticated. It is buried in result #5 though.

Example 2: The track is not found when using the API and authenticated.

Example 3: The track is not found in the rdio site search drop-down.

Together, this reduces the value of the API greatly. To build a playlist of popular songs programatically creates a list of cover versions and karaoke songs. Not exactly the sort of playlist that inspires maintaining a 'paid' subscription.

![example1](https://f.cloud.github.com/assets/137759/1637340/372b8258-57e5-11e3-88cb-b4e36e9afbcb.png)

![example2](https://f.cloud.github.com/assets/137759/1637341/3b19a1c4-57e5-11e3-9532-493f3dd3a975.png)

![example3](https://f.cloud.github.com/assets/137759/1637342/3fde0fe2-57e5-11e3-8d16-5a3c6d22063f.png)

**Comment by sastraxi** [comment]
Thanks for the additional information Ryan. I can confirm that the issue is back and affecting us once more.

Can we get a reply from the Rdio team? This is quite disruptive as you can imagine!

**Comment by dasevilla** [comment]
Thanks for the detailed examples, they are helping with our investigation. We hope to have a solution soon.

**Comment by dasevilla** [comment]
Search now returns better results. The issue was that play counts were not affecting the ranking of tracks. This caused tribute/covers albums to rank higher than the original tracks. The team is continuing to improve the quality of search results, but your experience should be much better now.
