### ISSUE TITLE
API Console not working?

### ISSUE THREAD

**Issue by BronzePointKrel** [rdio/api#105]
http://rdioconsole.appspot.com/

Two issues: 
1. All requests get this response: Server Error: HTTPError()
2. The 'login' link leads to 'server error' message
   http://rdioconsole.appspot.com/login

![one](https://f.cloud.github.com/assets/137759/1634323/276faa8a-5798-11e3-8795-6114b73338c8.png)
![two](https://f.cloud.github.com/assets/137759/1634324/276fe6bc-5798-11e3-9e0a-cc2c8c6b3dce.png)

**Comment by dasevilla** [comment]
It went over the default rate limits, increasing the limits fixed the issue. Thanks for the report!
