### ISSUE TITLE
iOS SDK: RDPlayer.duration not KVO compliant

### ISSUE THREAD

**Issue by potatolicious** [rdio/api#106]
Hello Rdio!

I'm working on an app using the SDK, and noticed RDPlayer.duration is not KVO compliant. It would be nice to have this feature.

We can re-fetch the duration upon track change, but for the sake of simplicity it'd be valuable to have all properties be KVO compliant so relevant UI widgets can subscribe directly to only the events they care about.

**Comment by rknLA** [comment]
Hi @potatolicious, thanks for reporting this.  I haven't had a chance to investigate yet, but if it's something we can do, we'll put it into the next SDK release.

**Comment by dasevilla** [comment]
This is fixed in v2.0.0

http://blog.rdio.com/developers/2014/05/ios-sdk-20-migration-guide.html
