### ISSUE TITLE
[Android] Rdio#signUp(String, String) throws ConcurrentModificationException

### ISSUE THREAD

**Issue by ghost** [rdio/api#108]
When Rdio#signUp is called from a background task, and passed a valid email address and an affiliate link generated by linkshare's deep linking tool, like so:

```
rdio.signUp(email, affiliateLink);
```

a ConcurrentModificationException is thrown:

```
 01-03 15:48:24.159: A/RdioApi(17773): java.util.ConcurrentModificationException
 01-03 15:48:24.159: A/RdioApi(17773):  at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
 01-03 15:48:24.159: A/RdioApi(17773):  at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:960)
 01-03 15:48:24.159: A/RdioApi(17773):  at com.rdio.android.api.internal.u.a(Unknown Source)
 01-03 15:48:24.159: A/RdioApi(17773):  at com.rdio.android.api.Rdio.signUp(Unknown Source)
```

Replacing the "offerid" part of the affiliate link with "bids" seems to correct it:

```
rdio.signUp(email, affiliateLink.replace("&offerid=", "&bids="));
```

**Comment by dasevilla** [comment]
This method is no longer in the Android SDK. Uses can sign up for Rdio during the web authorization flow.

http://blog.rdio.com/developers/2015/06/android-sdk-v302.html
