### ISSUE TITLE
Android SDK: getDuration always seem to return 0

### ISSUE THREAD

**Issue by benlc** [rdio/api#110]
Currently working on a player supporting multiple sources of playback, including Rdio. I'm doing very similar things with the native MediaPlayer and RdioPlayer, and am able to retrieve a track duration with MediaPlayer, but not with RdioPlayer ( both with Rdio app installed/uninstalled, account linked/not linked).

Here is one example :
            mRdioPlayer.setOnPreparedListener(new OnPreparedListener() {
                @Override
                public void onPrepared(MediaPlayer mItunesPlayer) {
                        Logger.e(TAG, "total duration: " + mRdioPlayer.getDuration());
                }
            });

Log will print 0. Calling getDuration during the playback will have the same result. I've been using the 1.1 sdk

**Comment by dasevilla** [comment]
I can confirm this is an issue and that we're investigating a solution. A workaround would be to use the `duration` field on the Track object returned by the API.

**Comment by benlc** [comment]
Thanks Devin, our servers are an intermediary between our clients and Rdio's API, I'll see with the team tomorrow if we can retrieve the duration from there, otherwise I guess we might have to go for single queries each time we want to play something

**Comment by dasevilla** [comment]
I spoke to our mobile team and it seems that the the `getDuration` method doesn't work consistently since it is dependent on the OEM to implement properly. In our official apps, we just use the duration from the metadata as well.

**Comment by benlc** [comment]
Thanks for these infos. Just a heads up, getDuration from other sources work just fine when Rdio's doesn't on our test device. We're going toward the metadata as well, thanks for your help

**Comment by dasevilla** [comment]
This also causes #114.

**Comment by quentin41500** [comment]
Is this still an issue ? I'm trying to find a way to use it the seekTo method, is there any other way to make it work ?

**Comment by dasevilla** [comment]
Duration works properly in the latest version of the Android SDK

http://blog.rdio.com/developers/2015/06/android-sdk-v302.html
