### ISSUE TITLE
RDPlayerState should include a buffering state

### ISSUE THREAD

**Issue by Pavan96** [rdio/api#111]
Hi,
I am working with rdio api in my iOS App. While playing a song from using track key 
sudddenly it stops but streaming is going on. Its like buffering ,stops and agian buffering so that song playiing with interrupts . It may be internert speed in this case how should I check it stops buffering . Any rdio delegate method for this ?? Any help will be appreciated.
Using code for playing
        [[AppDelegate rdioInstance].player playSource:key];

I console after I play song I got this log 

Reachability Flag Status: -R ------d localWiFiStatusForFlags
info kAudioFileStreamProperty_MagicCookieData err ?knu 1970170687

**Comment by dasevilla** [comment]
The `rdioPlayerChangedFromState:toState:` method on `RDPlayerDelegate` will tell you about transitions, but it does not currently have a separate buffering state. I've noted that as an improvement we could add.

**Comment by dasevilla** [comment]
The latest iOS SDK has a buffering state.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
