### ISSUE TITLE
rdioPlayerCouldNotStreamTrack doesn't get called when prebuffering tracks

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#112]
It gets called fine in response to `playSource`, but does not get called correctly when it attempts to prebuffer an unstreamable source while another source is playing

**Comment by mmase** [comment]
This seems to be the case for me as well. If I call for the next track before prebuffer occurs, the queue moves on to the next song if the track is unstreamable. If the SDK has a chance to try to prebuffer the unstreamable track, it gets stuck.

**Comment by rknLA** [comment]
@masedesign Yep, that's what we've noticed as well.  We've got a patch for it in code review now, and will be releasing a fix soon.

**Comment by rknLA** [comment]
This is fixed in [v1.3.6](http://on.rdio.com/1hgwyRF)
