### ISSUE TITLE
seekTo(int msec)

### ISSUE THREAD

**Issue by dhkout** [rdio/api#114]
Because the MediaPlayer returned by Rdio SDK returns getDuration()=0, it seems like the seekTo(int msec) is not working as well. Is there a workaround for this?

**Comment by dasevilla** [comment]
Currently there isn't a workaround for this issue. We are looking into how to resolve this issue.

**Comment by mrmaffen** [comment]
Quite a dealbreaker for me. Would be highly appreciated if you guys could fix this bug soon ... SeekTo is a very basic feature after all ...

**Comment by Miges** [comment]
Hello, have there been any advances WRT this issue?  This is a major problem.

**Comment by quentin41500** [comment]
Is this still an issue ? I'm trying to find a way to use it, is there any other way to make it work ?

**Comment by Miges** [comment]
Hi Quentin,

I cannot remember for sure as it was a while ago that I last looked at this stuff but... from memory if you let the whole song download first (i.e. buffer into the Player object) then it will allow you to seek.

Regards,
Miges

**Comment by dasevilla** [comment]
Seek works properly in the newest Android SDK

http://blog.rdio.com/developers/2015/06/android-sdk-v302.html
