### ISSUE TITLE
[iOS] seekToPosition changes playback state without delegate callback

### ISSUE THREAD

**Issue by potatolicious** [rdio/api#116]
Hi Rdio,

I'm experiencing a problem that may be a bug. When in a paused state, seekToPosition resumes playback.

I don't believe this is expected behavior - but in any case, the resumption of playback is not accompanied by a call to the delegate's rdioPlayerChangedFromState selector, so there is no way for me to update my UI to reflect that sound is playing.

The resumption of playback is also not being reflected in the position value on RDPlayer.

IMO seekToPosition should not restart playback if it is currently paused, or if so it should issue the correct state change callbacks so the developer can handle.

**Comment by rknLA** [comment]
Hi @potatolicious,

Thanks for the report.  You're totally right, at least one of those two things should happen!  I'll have a look shortly to see if there's anything we can do about fixing this in the near term.

Best,
Kevin

**Comment by dasevilla** [comment]
Fixed in v2.1.0

http://blog.rdio.com/developers/2014/06/ios-sdk-v210.html
