### ISSUE TITLE
Keep getting 503 error from server

### ISSUE THREAD

**Issue by ipartola** [rdio/api#125]
The request I am trying to make is a POST to http://api.rdio.com/1/ with the data count=10000&extras=bigIcon1200%2CbigIcon%2Cicon400&method=getNewReleases&time=thisweek.

**Comment by dasevilla** [comment]
Are you signing the request using OAuth? 

http://www.rdio.com/developers/docs/web-service/oauth/

**Comment by dasevilla** [comment]
Also, the `count` parameter is set to a really high value. It's recommended you use a smaller value and paginate if you need more results.

**Comment by ipartola** [comment]
Perhaps the count param being too high is the issue. I has been working for about a year but seems to have stopped about two weeks ago. I am using the unofficial Python client: https://github.com/kreeger/python-rdio which uses OAuth.

**Comment by dasevilla** [comment]
That's most likely the issue, returning 10,000 items is a lot (I'm surprised it worked to begin with). I recommend using pagination to get the full list.
