### ISSUE TITLE
Is Queue is pre bufferd 

### ISSUE THREAD

**Issue by noman-iqbal** [rdio/api#126]
i m using Rdio Ios sdk and want to confirm that if we use queue then "Is it pre buffer tracks or not" ?

there is an issue that i feel is happening , when i listen some songs from queue then some song's plays for 1.5 sec and then pause for 1 sec and then rest of song play fluently.

**Comment by dasevilla** [comment]
I've replied to your [email on the mailing list](https://groups.google.com/d/msg/rdio-api/WkUq7BE8Y4c/pEiytiNT7GAJ).
