### ISSUE TITLE
iOS SDK naming collision when using Swift

### ISSUE THREAD

**Issue by potatolicious** [rdio/api#128]
Hey Rdio,

Working on a Swift codebase using the iOS lib and running into a bad naming collision. It looks like there is both a protocol and a class named "RDAPIRequestDelegate". This worked fine in Obj-C land where there's no way for protocol and class names to be used in the same context, but in Swift this results in the inability to access the protocol at all.

```
class RdioResponder: NSObject, RDAPIRequestDelegate { ...
```

Results in a "multiple inheritance" error from the compiler, since it is looking at RDAPIRequestDelegate the class. There doesn't appear to be a way to point the compiler at the protocol instead here.

Ideas on fixes?

**Comment by dasevilla** [comment]
I think you're the first person to try the iOS SDK with Swift! We'll look into this issue, thanks for the report.

**Comment by dasevilla** [comment]
One of our mobile developers was able to create a sample Swift application: https://github.com/rdio/hello-ios-swift
