### ISSUE TITLE
[Android] Rdio login with facebook

### ISSUE THREAD

**Issue by AdrianHarr** [rdio/api#134]
I have been working with the Android SDK, and recently noticed that if I do not have the facebook app installed, logging into rdio with facebook does not work. After I press the facebook login button, the UI clears to a white screen, with no change in state from rdio. 
Here is how I made the login:

Intent rdioIntent = new Intent(this, OAuth1WebViewActivity.class);
rdioIntent.putExtra(OAuth1WebViewActivity.EXTRA_CONSUMER_KEY, APP_KEY);
            rdioIntent.putExtra(OAuth1WebViewActivity.EXTRA_CONSUMER_SECRET, APP_SECRET);
            this.startActivityForResult(rdioIntent, RDIO_INTENT_REQUEST_CODE);

**Comment by dasevilla** [comment]
Following up to let you know that we've been able to reproduce this issue. We haven't figured out the cause yet.

**Comment by dasevilla** [comment]
Please upgrade to the latest version of the Android SDK, it relies on OAuth 2.0 and Facebook login is working.

http://blog.rdio.com/developers/2015/06/android-sdk-v302.html
