### ISSUE TITLE
[iOS] The login screen will not load

### ISSUE THREAD

**Issue by Vaalla42** [rdio/api#139]
Almost every time I show the login screen  the spinner will remain forever and the login forms will not show up.
![ios simulator screen shot 04 dec 2014 16 21 48](https://cloud.githubusercontent.com/assets/1549267/5299624/b0aee9ce-7bd1-11e4-8d12-dd0d70b5f794.png)

**Comment by dasevilla** [comment]
Thanks for writing in! A few questions:
- Are you receiving an NSError via `rdioAuthorizationFailed`?
- If so, can you see if it's a network timeout?
- What type of connection are you on?
- Where in the world are you?

**Comment by Vaalla42** [comment]
- I don't get NSError via rdioAuthorizationFailed
- How I check this?
- Ethernet with the simulator and wifi with the device
- Romania (East Europa)

**Comment by dasevilla** [comment]
Thanks for the details, we're still investigating

**Comment by objectiveCarlo** [comment]
This is happening to me too, I also tried your iOS apps in here in github and they are not working also.

I don't get NSError via rdioAuthorizationFailed
There is no error so no way to find out the answer to this question..
Ethernet with the simulator and wifi with the device
Philippines (Manila) and Los Angeles, California

**Comment by minniTomar** [comment]
I have also found this error, I also tried your iOS apps from github and they are not working also.

I don't get NSError via rdioAuthorizationFailed
There is no error in console then how would I find this?.
Ethernet in simulator and wifi in device.
Noida (India)

**Comment by dasevilla** [comment]
We've deployed a fix for this issue.
