### ISSUE TITLE
Documentation needs revision

### ISSUE THREAD

**Issue by diegofrata** [rdio/api#14]
I've spotted some problems in the API documentation and it probably should be revised. Some highlights from the top of my head.
- The method getAlbumsForArtistInCollection states the object returned is an Album, but actually it returns an CollectionAlbum;
- There are some undocumented properties such as isProtected in User object,  or usingEchonest for stations;
- There are documented properties that are not being returned, such as collectionUrl in the CollectionArtist object.
- The search method needs more explained documentation as its *_count properties doesn't seem to ever match the way it's described in the documentation. (number_results doesn't match the sum of all other count fields).

**Comment by dasevilla** [comment]
Thanks for the feedback, I'll get it fixed. We are currently working on an expanded and improved version of the API documentation.

**Comment by dasevilla** [comment]
Reopening, I shouldn't have closed it yet since it's not fixed.

**Comment by dasevilla** [comment]
These issues are fixed on the new developer site: http://www.rdio.com/developers/docs/
