### ISSUE TITLE
[iOS] Rdio does not call delegates

### ISSUE THREAD

**Issue by objectiveCarlo** [rdio/api#141]
Always just logs: RDSession loginWithAccessToken:](103): Login already in progress

**Comment by rknLA** [comment]
Can you please provide steps to reproduce?  Including, if possible, your actual code, and what UI actions are required to make that happen?  It would also be helpful to know what your network strength is when this happens.

**Comment by dasevilla** [comment]
The latest iOS SDK uses OAuth 2.0 for login, this issue was specific to OAuth 1.0.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
