### ISSUE TITLE
getActivityStream add track to playlist events missing track ID

### ISSUE THREAD

**Issue by rlvoyer** [rdio/api#144]
Hi there,

The getActivityStream API returns a lot of information. However, the event objects corresponding to "add track to playlist" events are missing an important attribute: the identifier for the track being added. Is it possible to expose this information using the "extras" parameter? If not, is this information you would be willing to expose?

Thanks!
Robert

**Comment by rlvoyer** [comment]
Any chance you will be able to implement this any time soon?

**Comment by jnorton001** [comment]
This was added to the getActivitySteam API yesterday: "track" is now a key in the object for "add track to playlist" events, and can be manipulated via extras to include/exclude fields as needed. Enjoy!
