### ISSUE TITLE
iOS SDK 64bit support

### ISSUE THREAD

**Issue by minerat** [rdio/api#146]
According to https://github.com/rdio/api/issues/2, ARMv7s support was added to the SDK back in 2012.  However, I get the following error when including ARMv7s in my valid architectures.

ld: file is universal (4 slices) but does not contain a(n) armv7s slice: ./Rdio.framework/Rdio file './Rdio.framework/Rdio' for architecture armv7s

lipo confirms that armv7s is missing from the framework (3.1.4

xcrun -sdk iphoneos lipo -info Rdio.framework/Rdio
Architectures in the fat file: Rdio.framework/Rdio are: armv7 i386 x86_64 arm64

Here's the same command run against a recent Flurry library. 
xcrun -sdk iphoneos lipo -info Flurry/libFlurry_5.3.0.a
Architectures in the fat file: Flurry/libFlurry_5.3.0.a are: i386 x86_64 armv6 armv7 armv7s arm64

Can we get a version of the library with arm7s support?

**Comment by dasevilla** [comment]
I was able to reproduce this issue. Looks like this is related to a change made in Xcode 6 to not include `armv7s` by default anymore.

http://stackoverflow.com/questions/24040497/xcode-6-standard-architectures-exclude-armv7s
http://www.cocoanetics.com/2014/10/xcode-6-drops-armv7s/

**Comment by minerat** [comment]
Ahh, alright - that makes sense.  I'm still building on Xcode 5.x and standard architectures still includes armv7s.  If it's that insignificant, I'll remove it from my build - I don't have a special use case for it; I was just trying to get the standard build to work.  It'll be moot once on Xcode 6.  

Thanks!
