### ISSUE TITLE
[iOS] Status Bar issues on iOS 8 login view controller, fine on iOS 7

### ISSUE THREAD

**Issue by jarrodrobins** [rdio/api#147]
So I recall when iOS 7 came out, Rdio put out an update that pushes the view controller down 20 points to sit under the status bar. Great - this still works on iOS 7. 

However, it appears to revert to the incorrect behaviour on iOS 8.

I just tried this with the "Hello iOS Playback" sample app and the result is the same as in my app. 

Doesn't look ideal...

**iOS 7.1**
![ios simulator screen shot 26 mar 2015 3 17 45 pm](https://cloud.githubusercontent.com/assets/1313663/6840406/8888c8be-d3cb-11e4-9f9c-a3a81c4e53ba.png)

**iOS 8.2**
![ios simulator screen shot 26 mar 2015 3 17 27 pm](https://cloud.githubusercontent.com/assets/1313663/6840408/93b6d230-d3cb-11e4-99c0-88f2e3f59adb.png)

**Comment by dasevilla** [comment]
The latest iOS SDK has a fix for this issue.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
