### ISSUE TITLE
Wrong handling of fragment in callback URL

### ISSUE THREAD

**Issue by luisgerhorst** [rdio/api#152]
I noticed that your API redirects the user to `http://site.com/#frament?oauth_verifier=1234&oauth_token=xyz` instead of `http://site.com/?oauth_verifier=1234&oauth_token=xyz#frament` after successful authorisation.
I know this is not very critical but it would be nice anyway and would simplify the design of my app (the solution now is a little hacky).

**Comment by dasevilla** [comment]
We've deprecated OAuth 1.0 and are moving developers to OAuth 2.0, checkout the [launch announcement](http://blog.rdio.com/developers/2015/06/oauth-20-launch.html).
