### ISSUE TITLE
iOS OAuth v2 Issues

### ISSUE THREAD

**Issue by ungureanuli** [rdio/api#154]
I am updating an iOS app that is using the Rdio SDK from 2.1.4 to 3.0.2. On the 2.1.4 the login flow works good.
Note: The iOs app is saving the Rdio tokens on the server side and use these to re-login the user on the same or on a different device (iOS or Android).

After following the recommended steps from http://www.rdio.com/developers/docs/guides/oauth2-migration/ the main issues I encountered are:
1. After a successful login the delegate method rdioDidAuthorizeUser:withAccessToken: gets called but the accessToken is nil (even though for this method there is the comment "Authenticating with an OAuth 2.0 client will result in `rdioDidAuthorizeUser:` getting called instead." )
   <b>What method should I use to get an instance of AFOAuthCredential?</b>
   As a temporary solution I can send a notification from the success block in the authenticateUsingOAuthWithURLString:parameters:success:failure: method (AFOAuth2Manager.h)
   and on the rdioDidAuthorizeUser: delegate method to use the AFOAuthCredential object previously notified to be saved.
2. I can create an AFOAuthCredential object form the tokens (saved as described above) and re-login with the authorizeUsingAccessToken: method.
   " @param accessToken Either an NSString token received from a previous <code>rdioDidAuthorizeUser:withAccessToken:</code> delegate call, or an AFOAuthCredential including the relevant OAuth 2.0 access and refresh token information."
   Everything works good (the rdioDidAuthorizeUser: gets called this time), until the access token expires.
   After the expiration date, this method does not work anymore (it hangs without even calling any delegate method back). 
   <b>Please advice me how should I handle the refresh token flow?</b>
   I did try to implement the refresh token flow, as described here http://www.rdio.com/developers/docs/web-service/oauth2/overview/ref-using-a-refresh-token but I get the error:
   
   > "Error Domain=AFNetworkingErrorDomain Code=-1011 "Request failed: bad request (400)" UserInfo=0x7a7072d0 {NSErrorFailingURLKey=https://services.rdio.com/oauth2/token, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x7be638f0> { URL: https://services.rdio.com/oauth2/token } { status code: 400, headers {
   > "Access-Control-Allow-Origin" = "*";
   > Connection = "keep-alive";
   > "Content-Language" = en;
   > "Content-Length" = 81;
   > "Content-Type" = "application/json";
   > Date = "Mon, 15 Jun 2015 09:45:08 GMT";
   > P3P = "CP=\"This is not a P3P policy. See http://www.rdio.com/legal/privacy-policy for more info.\"";
   > Server = "nginx/1.2.4";
   > "Set-Cookie" = "r=eyJfZSI6IDB9.TntV3ezgjIEgu4PtxiO8mTYQsJM; Domain=.rdio.com; Path=/";
   > Vary = "Accept-Language, Cookie";
   > "X-Version" = 720;
   > "X-srv" = "srv-207-09";
   > } }, NSLocalizedDescription=Request failed: bad request (400)}""

**Comment by dasevilla** [comment]
We did a deploy today that should have fixed the token issue, can you test again?

**Comment by ungureanuli** [comment]
I have a user logged in on Rdio with an expired token form 06-15:
- AFOAuthCredential: accessToken:"..." tokenType:"bearer" refreshToken:"..." expiration:"2015-06-15 22:00:00 +0000"

I have tried the following two options:
1. I tried calling the authorizeUsingAccessToken: method with this AFOAuthCredential objected, but I get the rdioAuthorizationFailed: delegate being called with the error:
   
   > Error Domain=RDErrorDomain Code=3 "Request failed: unauthorized (401)" UserInfo=0x15d96ad0 {NSErrorFailingURLKey=https://services.rdio.com/api/1/currentUser, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x15eda130> { URL: https://services.rdio.com/api/1/currentUser } { status code: 401, headers {
   > "Access-Control-Allow-Origin" = "*";
   > "Access-Control-Expose-Headers" = "x-rdio-api-version";
   > "Cache-Control" = "no-cache";
   > Connection = "keep-alive";
   > "Content-Language" = en;
   > "Content-Length" = 82;
   > "Content-Type" = "application/json";
   > Date = "Fri, 19 Jun 2015 07:54:29 GMT";
   > P3P = "CP=\"This is not a P3P policy. See http://www.rdio.com/legal/privacy-policy for more info.\"";
   > Server = "nginx/1.2.4";
   > Vary = "Accept-Language, Cookie";
   > "X-Version" = 720;
   > "X-srv" = "srv-211-09";
   > } }, NSLocalizedDescription=Request failed: unauthorized (401)}
2. Instead of directly calling the authorizeUsingAccessToken: I have created my own method for checking if the AFOAuthCredential object is expired and if so I am performing a call to trigger the refresh token using the 
   [oAuth2Manager authenticateUsingOAuthWithURLString:@"oauth2/token" parameters:parameters success:^(AFOAuthCredential *credential) {  } failure:^(NSError *error) {   }] method similar as the example presented in the OAuth v2 documentation: http://www.rdio.com/developers/docs/web-service/oauth2/overview/ref-oauth2-client-verification
   
   > POST /oauth2/token HTTP/1.1
   > Host: services.rdio.com
   > Content-Type: application/x-www-form-urlencoded
   > grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA
   > &client_id=s6BhdRkqt3&client_secret=7Fjfp0ZBr1KtDRbnfVdmIw

However the failure block gets called with the error:

> Error Domain=AFNetworkingErrorDomain Code=-1011 "Request failed: bad request (400)" UserInfo=0x146b1480 {NSErrorFailingURLKey=https://services.rdio.com/oauth2/token, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x146c8430> { URL: https://services.rdio.com/oauth2/token } { status code: 400, headers {
>     "Access-Control-Allow-Origin" = "*";
>     Connection = "keep-alive";
>     "Content-Language" = en;
>     "Content-Length" = 81;
>     "Content-Type" = "application/json";
>     Date = "Fri, 19 Jun 2015 08:09:12 GMT";
>     P3P = "CP=\"This is not a P3P policy. See http://www.rdio.com/legal/privacy-policy for more info.\"";
>     Server = "nginx/1.2.4";
>     "Set-Cookie" = "r=eyJfZSI6IDB9.TntV3ezgjIEgu4PtxiO8mTYQsJM; Domain=.rdio.com; Path=/";
>     Vary = "Accept-Language, Cookie";
>     "X-Version" = 720;
>     "X-srv" = "srv-211-09";
> } }, NSLocalizedDescription=Request failed: bad request (400)}

**Comment by ungureanuli** [comment]
It seems the issue was when passing the Rdio client secret ID (I was using the client ID instead). After correcting this, the solution from 2 is working good to refresh the access token.
Thank you Devin for your feedback.

**Comment by yourei** [comment]
@ungureanuli I am trying to do the same thing and I keep getting a 400 error saying it is a bad request. Do you mind posting the call you are making with oAuth2Manager authenticateUsingOAuthWithURLString? I am setting the client_id and client_secret in the parameters. Do I have to set something else in the authorization header?
Thanks!

**Comment by yourei** [comment]
@ungureanuli  - Nevermind, I had to specify "refresh_token" as the grant in the parameters along with the refresh_token as well. I mis-read the documentation. Thanks!

**Comment by zeeshan-ahmad-butt** [comment]
@ungureanuli @dasevilla 
I got following response while i try to login into Rdio from My website. Now i want to use following response into my IOS app and want to Login throgh (void)authorizeUsingAccessToken:(id)accessToken;
What is the Parameter format for (id)accessToken ? How can i use above method by using following response.

{"access_token"=>"AAAAAWEAAAAAAixfMQAAAIBV0whcVdOxHAAAABozdGR4enhoYTJmY3o1amh4M2Zzb3I3ZTJveWSLqxBFaLBE7vBxq0EtGKb0hYfhZVw4Q6aM4XhNEZCr", "token_type"=>"bearer", "expires_in"=>43200, "refresh_token"=>"AAAAAXIAAAAAAixfMQAAAIBV0whce2sOXAAAABozdGR4enhoYTJmY3o1amh4M2Zzb3I3ZTJveb0lZpsdV6olWeh_v5NdIWlEV2A3DqFXQFXyTVRbQwn3", "scope"=>"shared_playstate"}

**Comment by zeeshan-ahmad-butt** [comment]
#import “AFOAuth2Manager.h”
 AFOAuthCredential *accessToken = [AFOAuthCredential credentialWithOAuthToken:"AAAAAWEAAAAAAixfMQAAAIBV0whcVdOxHAAAABozdGR4enhoYTJmY3o1amh4M2Zzb3I3ZTJveWSLqxBFaLBE7vBxq0EtGKb0hYfhZVw4Q6aM4XhNEZCr" tokenType:kAFOAuthCodeGrantType];
 [_rdio authorizeUsingAccessToken:accessToken];

I got following response when make the Above Request.

Error Domain=RDErrorDomain Code=3 "Request failed: forbidden (403)" UserInfo=0x7fd15211b650 {NSLocalizedDescription=Request failed: forbidden (403), NSErrorFailingURLKey=https://services.rdio.com/api/1/currentUser, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x7fd151566a40> { URL: https://services.rdio.com/api/1/currentUser } { status code: 403, headers {
    Connection = "keep-alive";
    "Content-Language" = en;
    "Content-Length" = 22;
    "Content-Type" = "text/plain";
    Date = "Wed, 30 Sep 2015 15:22:29 GMT";
    P3P = "CP=\"This is not a P3P policy. See http://www.rdio.com/legal/privacy-policy for more info.\"";
    Server = "nginx/1.2.4";
    Vary = "Accept-Language, Cookie";
    "Www-Authenticate" = "OAuth realm=\"http://api.rdio.com/\"";
    "X-Version" = 720;
    "X-srv" = "srv-211-08";
} }, NSUnderlyingError=0x7fd152141700 "Request failed: unacceptable content-type: text/plain"}
