### ISSUE TITLE
Rdio Web Service API

### ISSUE THREAD

**Issue by hjylewis** [rdio/api#159]
my getPlaybackToken is returning

`"\n<!DOCTYPE html>\n<html>\n  <head>   \n    <title>Rdio - Error</title>\n    <meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\n    <meta name=\"description\" content=\"Rdio lets you listen to millions of songs ad-free wherever you are – on the web and on your phone, even offline.\" />\n    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>\n\n    \n    <style type=\"text/css\">\n      body {\n        background-color: #f6f6f7;\n        margin: 0;\n        padding: 0;\n        font-size: 16px;\n        color: #4B5C66;\n        font-family: \"Lucida Grande\", Arial, Helvetica, sans-serif;\n        line-height: 1.5;\n      }\n      .wrapper .inner-wrapper {\n        min-height: 725px;\n        padding: 0 0 200px;\n      }\n      .wrapper, .inner-wrapper {\n        position: absolute;\n        top: 0;\n        bottom: 0;\n        left: 0;\n        right: 0;\n      }\n      #header {\n        padding: 75px 0 30px;\n      }\n      h1 {\n        text-align: center;\n      }\n      #header h1 a {\n        display: inline-block;\n        width: 84px;\n        height: 32px;\n        background: url(\"http://i.imgur.com/G2M4W.png\") no-repeat;\n      }\n      .dialog {\n        width: 600px;\n        margin: 0px auto;\n        padding: 0;\n        color: #4B5C66;\n        font-size: 14px;\n      }\n      .dialog h2 {\n        font-size: 32px;\n        font-family: \"Open Sans\", Arial, Helvetica, sans-serif;\n        font-weight: 300;\n        text-align: center;\n        margin: 0;\n        line-height: 100%;\n      }\n      .dialog p {\n        text-align: center;\n        padding: 0 45px;\n      }\n    </style>\n    \n  </head>\n  \n    <body class=\"Dialogs\">\n\n    <div class=\"wrapper\">\n      <div class=\"inner-wrapper\">\n\n\n        <div id=\"header\">\n          <h1><a href=\"/\" title=\"Rdio\"></a></h1>\n        </div>\n        \n        \n        <div class=\"dialog \">\n        \n          <div class=\"dialog-content\">\n            \n          <!-- critical-theoopspageisshowing -->\n          <h2>Oops!</h2>\n          <p>Sorry &mdash; something has gone wrong.<br/>We've logged an error and it will be fixed as soon as possible.</p>\n        \n          </div> \n        \n        </div>\n\n        \n      </div>\n    </div>\n\n    \n  </body>\n</html>\n"`

**Comment by dasevilla** [comment]
This error is intentional, we have disabled OAuth 1.0. See the [announcement on the Developer Blog](http://blog.rdio.com/developers/2015/06/oauth-20-launch.html).
