### ISSUE TITLE
Android API doesn't work with new Rdio Android Application

### ISSUE THREAD

**Issue by mlegris** [rdio/api#16]
You updated your application two days ago. Ever since, your Android API doesn't work well at all when the Application is present. If you uninstall it all works fine. Otherwise, all hell breaks loose. Nothing works, no authentication, api call, playback. Nada.

**Comment by hwrdprkns** [comment]
I will investigate the legitimacy of this bug in the next few days or so—I don't think anything around intent handling changed, but I will make sure.

**Comment by hwrdprkns** [comment]
Ah, you're correct. I'll look into fixing this as soon as possible.

**Comment by mlegris** [comment]
thanks! I have a few tablets around, and the ones with the new rdio app
don't work, yet the ones with the old ones work like a charm.

There is also a weird hanging bug that happens when playing a song, i can't
reproduce it yet. But it happens. I'll try to get steps. Thanks!

M

**Comment by mlegris** [comment]
Any ETA? thanks

**Comment by hwrdprkns** [comment]
@mlegris : Hello, this issue has been fixed and should be in the next Android release. If not at the end of this week, then early next week. 

Thanks for your patience, and reporting this bug.

**Comment by milleph** [comment]
Hasn't resolved the issue for me - both Nexus 7 and Razr Maxx not working....

**Comment by tberman** [comment]
@hwrdprkns can you look at this again please.

**Comment by milleph** [comment]
thank you for reopening

**Comment by milleph** [comment]
Recap:

On Razr Maxx running ICS
     - if Rdio app is installed nothing works - no authentication, api call, playback - nada.
     - if Rdio app is not installed, samples play fine and MediaPlayer.getDuration() returns correct length

On Nexus 7 running JellyBean
     - if Rdio app is installed nothing works - no authentication, api call, playback - nada.
     - if Rdio app is not installed, samples play fine BUT MediaPlayer.getDuration() returns 0

**Comment by dasevilla** [comment]
@milleph, can you attach a log file to this issue or email it to developersupport@rd.io?

**Comment by milleph** [comment]
So, with Rdio app installed, fresh reboot of Nexus 7, my app's logcat in Eclipse, filtered on rdio

01-08 07:58:53.920: I/RdioAPI(2742): Preparing to init.
01-08 07:58:56.740: I/RdioAPI(2742): Running init task.
01-08 07:58:56.750: I/RdioAPI(2742): Initializing
01-08 07:58:56.750: I/RdioAPI(2742): Connecting to Rdio app
01-08 07:58:56.760: I/RdioAPI(2742): Sent bind request
01-08 07:58:56.770: I/RdioAPI(2742): Waiting for Rdio app connection
01-08 07:58:57.550: I/RDIO(2906): Application: OnCreate
01-08 07:58:57.560: I/RDIO(2906): Application: Changed umask from 63 to 22
01-08 07:58:57.660: I/RDIO(2906): AndroidApplicationProcess: Foreground started; MemoryUsageLimit = 32 MB; MemoryClass = 64 MB
01-08 07:58:57.740: I/RDIO(2906): AndroidFileStorageProvider: Initializing (root_path=/storage/emulated/0/Android/data/com.rdio.android.ui/files, is_external=True)
01-08 07:58:57.740: I/RDIO(2906): AndroidFileStorageProvider: Initializing (root_path=/data/data/com.rdio.android.ui/app_files, is_external=False)
01-08 07:58:57.920: I/RDIO(2906): SqliteDatabase: WAL journal mode enabled
01-08 07:58:58.000: I/RDIO(2906): Session: Session initializing. Version 2.4.5, Device ID fde7477e-3224-4f17-a0d5-cd13918f7e27 (c04311c7-a503-4630-b3c6-a402a73a57d7)
01-08 07:58:58.390: I/RDIO(2906): SqliteDatabase: WAL journal mode enabled
01-08 07:58:58.490: I/RDIO(2906): SqliteObjectDatabase: Table definitions up to date at v11 (83d70076c4f82cc44b43e0485ecf8514)
01-08 07:58:58.510: I/RDIO(2906): Session: StartMigration: be654980-eb46-4408-b432-75d239228410 (total count = 1)
01-08 07:58:58.550: I/RDIO(2906): BsonMigration: Starting migration from BSON
01-08 07:58:58.550: I/RDIO(2906): Images: ImageStore store available: True
01-08 07:58:58.560: I/RDIO(2906): BsonMigration: Started timer for operation 'BSON model migration'
01-08 07:58:58.580: I/RDIO(2906): BsonMigration: Started timer for operation 'BSON index parsing'
01-08 07:58:58.580: I/RDIO(2906): BsonMigration: BSON index does not exist for migration: SyncedPlaylists
01-08 07:58:58.580: I/RDIO(2906): BsonMigration: BSON index does not exist for migration: SyncedArtists
01-08 07:58:58.580: I/RDIO(2906): BsonMigration: BSON index does not exist for migration: SyncedAlbums
01-08 07:58:58.590: I/RDIO(2906): BsonMigration: BSON index does not exist for migration: SyncedTracks
01-08 07:58:58.600: I/RDIO(2906): TIMER:BsonMigration: Timed operation 'BSON index parsing' took 0.006127 seconds.
01-08 07:58:58.600: I/RDIO(2906): OfflineAudio: ChangeReadyState: isReady=False
01-08 07:58:58.600: I/RDIO(2906): BsonMigration: Started timer for operation 'BSON model storage clear'
01-08 07:58:58.610: I/RDIO(2906): FileStorage: Clearing FileStore 'metadata'
01-08 07:58:58.620: I/RDIO(2906): TIMER:BsonMigration: Timed operation 'BSON model storage clear' took 0.017455 seconds.
01-08 07:58:58.620: I/RDIO(2906): BsonMigration: Started timer for operation 'BSON index storage clear'
01-08 07:58:58.620: I/RDIO(2906): FileStorage: Clearing FileStore 'indexes'
01-08 07:58:58.620: I/RDIO(2906): TIMER:BsonMigration: Timed operation 'BSON index storage clear' took 0.001435 seconds.
01-08 07:58:58.620: I/RDIO(2906): TIMER:BsonMigration: Timed operation 'BSON model migration' took 0.062839 seconds.
01-08 07:58:58.620: I/RDIO(2906): BsonMigration: Started timer for operation 'BSON audio playback key migration'
01-08 07:58:58.630: I/RDIO(2906): BsonOfflineAudioDatabase: no existing index, requesting index construction
01-08 07:58:58.630: I/RDIO(2906): BsonMigration: No BSON audio playback keys to migrate or error loading them (BuildIndex)
01-08 07:58:58.640: I/RDIO(2906): TIMER:BsonMigration: Timed operation 'BSON audio playback key migration' took 0.017134 seconds.
01-08 07:58:58.640: I/RDIO(2906): BsonMigration: Migrated 0 models
01-08 07:58:58.640: I/RDIO(2906): BsonMigration: Migrated 0 playback keys
01-08 07:58:58.640: I/RDIO(2906): BsonMigration: SQL models count: 0
01-08 07:58:58.640: I/RDIO(2906): BsonMigration: SQL audio count: 0
01-08 07:58:58.650: I/RDIO(2906): SyncController: Permitted: False, Possible: False, Reason:Migrating
01-08 07:58:58.680: I/RDIO(2906): SyncEngineStateUnavailable: OnEnter
01-08 07:58:58.700: W/RDIO(2906): Session: IsAuthenticated changed: NotAuthenticated->Authenticated. Look here if you find auth update problems.
01-08 07:58:58.700: I/RDIO(2906): RdioSecretService: Authentication state change: NotAuthenticated->Authenticated
01-08 07:58:58.820: I/RDIO(2906): Session: Session is initialized.
01-08 07:58:58.830: I/RDIO(2906): AndroidSession: Network available: WIFI
01-08 07:58:58.870: I/RDIO(2906): Session: Connection Status Changed: [None] -> [NetworkConnectionAvailable, RdioServiceAccessible]
01-08 07:58:58.870: I/RDIO(2906): Session: Connection Status Changed: [NetworkConnectionAvailable, RdioServiceAccessible] -> [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible]
01-08 07:58:58.870: I/RDIO(2906): RdioPlayerFrontend: Changing player implementation from None to Local
01-08 07:58:58.980: I/RDIO(2906): Session: OnMigrationStateChanged
01-08 07:58:58.980: I/RDIO(2906): SyncController: Permitted: True, Possible: False, Reason:Migrating
01-08 07:58:58.980: I/RDIO(2906): SyncEngineStateUnavailable: OnEnter
01-08 07:58:58.990: I/RDIO(2906): SyncService: Deferring lock update
01-08 07:58:59.030: I/RDIO(2906): Session: FinishMigration: be654980-eb46-4408-b432-75d239228410 (total count = 0)
01-08 07:58:59.040: I/RDIO(2906): OfflineAudio: UpdateState: both storage and audio database are available
01-08 07:58:59.040: I/RDIO(2906): SyncController: Permitted: True, Possible: False, Reason:NoStorage
01-08 07:58:59.040: I/RDIO(2906): SyncEngineStateUnavailable: OnEnter
01-08 07:58:59.040: I/RDIO(2906): SyncService: Deferring lock update
01-08 07:58:59.080: I/RDIO(2906): UpdateMonitor: CheckForUpdate: last check was 1/8/2013 11:37:21 AM
01-08 07:58:59.080: I/RDIO(2906): OfflineAudio: UpdateState: audio database loaded: Success
01-08 07:58:59.080: I/RDIO(2906): OfflineAudio: ChangeReadyState: isReady=True
01-08 07:58:59.080: I/RDIO(2906): UpdateMonitor: CheckForUpdate: Checking in about 2 seconds.
01-08 07:58:59.120: I/RDIO(2906): SubscriptionMonitor: Session.IsRdioServiceAccessible = True
01-08 07:58:59.120: I/RDIO(2906): SubscriptionMonitor: Received request to reload user. Reloading user in 2 seconds.
01-08 07:58:59.130: I/RDIO(2906): SyncController: Permitted: True, Possible: True, Reason:None
01-08 07:58:59.130: I/RDIO(2906): SyncEngine: Transitioning from Unavailable to Idle
01-08 07:58:59.130: I/RDIO(2906): SyncService: Deferring lock update
01-08 07:58:59.130: I/RDIO(2906): SyncEngineStateIdle: OnEnter
01-08 07:58:59.130: I/RDIO(2906): SyncService: Deferring lock update
01-08 07:58:59.140: I/RDIO(2906): SubscriptionMonitor: Session.IsRdioServiceAccessible = True
01-08 07:58:59.150: I/RDIO(2906): AndroidSession: Network available: WIFI
01-08 07:58:59.150: I/RDIO(2906): Session: OnMigrationStateChanged
01-08 07:58:59.150: I/RDIO(2906): OfflineStore: OfflineAudio state changed, invalidating offline state for all models
01-08 07:58:59.200: I/RdioAPI(2742): App service connection established
01-08 07:58:59.210: I/RdioAPI(2742): Got Rdio subscription type: UNLIMITED
01-08 07:58:59.530: I/RDIO(2933): Application: OnCreate
01-08 07:58:59.540: I/RDIO(2933): Application: Changed umask from 63 to 22
01-08 07:58:59.640: I/RDIO(2933): AndroidApplicationProcess: PlayerService started; MemoryUsageLimit = 32 MB; MemoryClass = 64 MB
01-08 07:58:59.690: E/RDIO(2906): HttpClient: Exception getting request stream: Hyena.Net.HttpWebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
01-08 07:58:59.690: E/RDIO(2906):   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in <filename unknown>:0 
01-08 07:58:59.690: E/RDIO(2906):   at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
01-08 07:58:59.690: E/RDIO(2906):   --- End of inner exception stack trace ---
01-08 07:58:59.690: E/RDIO(2906):   at Hyena.Net.ManagedHttpWebRequest.Hyena.Net.IHttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:58:59.690: E/RDIO(2906):   at Hyena.Net.HttpClient+<PerformHttp>c__AnonStorey27.<>m__F (IAsyncResult result) [0x00000] in <filename unknown>:0 
01-08 07:58:59.730: I/RDIO(2933): AndroidFileStorageProvider: Initializing (root_path=/storage/emulated/0/Android/data/com.rdio.android.ui/files, is_external=True)
01-08 07:58:59.730: I/RDIO(2933): AndroidFileStorageProvider: Initializing (root_path=/data/data/com.rdio.android.ui/app_files, is_external=False)
01-08 07:58:59.800: E/RDIO(2906): HttpClient: Exception getting request stream: Hyena.Net.HttpWebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
01-08 07:58:59.800: E/RDIO(2906):   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in <filename unknown>:0 
01-08 07:58:59.800: E/RDIO(2906):   at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
01-08 07:58:59.800: E/RDIO(2906):   --- End of inner exception stack trace ---
01-08 07:58:59.800: E/RDIO(2906):   at Hyena.Net.ManagedHttpWebRequest.Hyena.Net.IHttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:58:59.800: E/RDIO(2906):   at Hyena.Net.HttpClient+<PerformHttp>c__AnonStorey27.<>m__F (IAsyncResult result) [0x00000] in <filename unknown>:0 
01-08 07:58:59.870: I/RDIO(2933): SqliteDatabase: WAL journal mode enabled
01-08 07:58:59.890: E/RDIO(2906): HttpClient: Exception getting request stream: Hyena.Net.HttpWebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
01-08 07:58:59.890: E/RDIO(2906):   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in <filename unknown>:0 
01-08 07:58:59.890: E/RDIO(2906):   at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0 
01-08 07:58:59.890: E/RDIO(2906):   --- End of inner exception stack trace ---
01-08 07:58:59.890: E/RDIO(2906):   at Hyena.Net.ManagedHttpWebRequest.Hyena.Net.IHttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:58:59.890: E/RDIO(2906):   at Hyena.Net.HttpClient+<PerformHttp>c__AnonStorey27.<>m__F (IAsyncResult result) [0x00000] in <filename unknown>:0 
01-08 07:58:59.890: W/RDIO(2906): HttpClient: ClearResponseTimeout called at un unexpected time
01-08 07:58:59.930: I/RDIO(2933): Session.BG: Session initializing. Version 2.4.5, Device ID fde7477e-3224-4f17-a0d5-cd13918f7e27 (254d7a2d-2e12-4e31-8474-0765b00be2fc)
01-08 07:59:00.360: I/RDIO(2933): SqliteDatabase.BG: WAL journal mode enabled
01-08 07:59:00.460: I/RDIO(2933): SqliteObjectDatabase.BG: Table definitions up to date at v11 (83d70076c4f82cc44b43e0485ecf8514)
01-08 07:59:00.470: I/RDIO(2933): Session.BG: StartMigration: 513363b4-87c8-4e4c-a020-5103cf9d9ca1 (total count = 1)
01-08 07:59:00.510: I/RDIO(2933): BsonMigration.BG: Starting migration from BSON
01-08 07:59:00.510: I/RDIO(2933): BsonMigration.BG: Started timer for operation 'BSON model migration'
01-08 07:59:00.530: I/RDIO(2933): Images.BG: ImageStore store available: True
01-08 07:59:00.540: I/RDIO(2933): BsonMigration.BG: Started timer for operation 'BSON index parsing'
01-08 07:59:00.540: I/RDIO(2933): OfflineAudio.BG: ChangeReadyState: isReady=False
01-08 07:59:00.540: I/RDIO(2933): BsonMigration.BG: BSON index does not exist for migration: SyncedPlaylists
01-08 07:59:00.540: I/RDIO(2933): BsonMigration.BG: BSON index does not exist for migration: SyncedArtists
01-08 07:59:00.540: I/RDIO(2933): BsonMigration.BG: BSON index does not exist for migration: SyncedAlbums
01-08 07:59:00.540: I/RDIO(2933): BsonMigration.BG: BSON index does not exist for migration: SyncedTracks
01-08 07:59:00.540: W/RDIO(2933): Session.BG: IsAuthenticated changed: NotAuthenticated->Authenticated. Look here if you find auth update problems.
01-08 07:59:00.550: I/RDIO(2933): TIMER:BsonMigration.BG: Timed operation 'BSON index parsing' took 0.007466 seconds.
01-08 07:59:00.550: I/RDIO(2933): RdioSecretService.BG: Authentication state change: NotAuthenticated->Authenticated
01-08 07:59:00.560: I/RDIO(2933): BsonMigration.BG: Started timer for operation 'BSON model storage clear'
01-08 07:59:00.560: I/RDIO(2933): FileStorage.BG: Clearing FileStore 'metadata'
01-08 07:59:00.570: I/RDIO(2933): TIMER:BsonMigration.BG: Timed operation 'BSON model storage clear' took 0.011743 seconds.
01-08 07:59:00.570: I/RDIO(2933): BsonMigration.BG: Started timer for operation 'BSON index storage clear'
01-08 07:59:00.570: I/RDIO(2933): FileStorage.BG: Clearing FileStore 'indexes'
01-08 07:59:00.570: I/RDIO(2933): TIMER:BsonMigration.BG: Timed operation 'BSON index storage clear' took 0.000948 seconds.
01-08 07:59:00.570: I/RDIO(2933): TIMER:BsonMigration.BG: Timed operation 'BSON model migration' took 0.061371 seconds.
01-08 07:59:00.570: I/RDIO(2933): BsonMigration.BG: Started timer for operation 'BSON audio playback key migration'
01-08 07:59:00.580: I/RDIO(2933): BsonOfflineAudioDatabase.BG: no existing index, requesting index construction
01-08 07:59:00.580: I/RDIO(2933): BsonMigration.BG: No BSON audio playback keys to migrate or error loading them (BuildIndex)
01-08 07:59:00.580: I/RDIO(2933): TIMER:BsonMigration.BG: Timed operation 'BSON audio playback key migration' took 0.00843 seconds.
01-08 07:59:00.580: I/RDIO(2933): BsonMigration.BG: Migrated 0 models
01-08 07:59:00.580: I/RDIO(2933): BsonMigration.BG: Migrated 0 playback keys
01-08 07:59:00.580: I/RDIO(2933): BsonMigration.BG: SQL models count: 0
01-08 07:59:00.590: I/RDIO(2933): BsonMigration.BG: SQL audio count: 0
01-08 07:59:00.670: I/RDIO(2933): Session.BG: Session is initialized.
01-08 07:59:00.690: I/RDIO(2933): AndroidSession.BG: Network available: WIFI
01-08 07:59:00.700: I/RDIO(2933): Session.BG: Connection Status Changed: [None] -> [NetworkConnectionAvailable, RdioServiceAccessible]
01-08 07:59:00.710: I/RDIO(2933): UserEventLog.BG: Loading from storage
01-08 07:59:00.710: I/RDIO(2933): Session.BG: Connection Status Changed: [NetworkConnectionAvailable, RdioServiceAccessible] -> [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible]
01-08 07:59:00.710: I/RDIO(2933): RdioPlayerBackend.BG: RdioPlayerBackend implementation installed
01-08 07:59:00.730: I/RDIO(2933): PubSubConnection.BG: Registering RdioPlayerBackend
01-08 07:59:00.740: I/RDIO(2933): PubSubConnection.BG: State change Disconnected -> Connecting
01-08 07:59:00.750: I/RDIO(2933): UserEventLog.BG: Finished loading events
01-08 07:59:01.020: I/RDIO(2933): AudioStreamHttpProxy.BG: Starting
01-08 07:59:01.610: I/RDIO(2933): Session.BG: OnMigrationStateChanged
01-08 07:59:01.620: I/RDIO(2933): Session.BG: FinishMigration: 513363b4-87c8-4e4c-a020-5103cf9d9ca1 (total count = 0)
01-08 07:59:01.620: I/RDIO(2933): OfflineAudio.BG: UpdateState: both storage and audio database are available
01-08 07:59:01.630: I/RDIO(2933): AndroidSession.BG: Network available: WIFI
01-08 07:59:01.630: I/RDIO(2933): Session.BG: OnMigrationStateChanged
01-08 07:59:02.150: I/RDIO(2933): Session.BG: Connection Status Changed: [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible] -> [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible]
01-08 07:59:02.510: I/RDIO(2933): OfflineAudio.BG: UpdateState: audio database loaded: Success
01-08 07:59:02.510: I/RDIO(2933): OfflineAudio.BG: ChangeReadyState: isReady=True
01-08 07:59:02.620: I/RDIO(2906): UpdateMonitor: HandleVersionInformation: MarketplaceIdentifiers=[market://details?id=com.rdio.android.ui], RunningVersion=2.4.5, LatestVersion=2.2.8, MinimumRequiredVersion=
01-08 07:59:03.190: I/RDIO(2933): Sequencer.BG: Shuffling indices with initial index=0
01-08 07:59:03.210: I/RDIO(2933): Session.BG: Connection Status Changed: [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible] -> [NetworkConnectionAvailable, WifiConnectionAvailable, RdioServiceAccessible]
01-08 07:59:03.310: I/RDIO(2906): PlayerStateManager: Reloading state from JSON
01-08 07:59:03.590: E/RDIO(2933): HttpClient.BG: Exception getting request stream: Hyena.Net.HttpWebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Bad record MAC
01-08 07:59:03.590: E/RDIO(2933):   at Mono.Security.Protocol.Tls.RecordProtocol.decryptRecordFragment (ContentType contentType, System.Byte[] fragment) [0x00000] in <filename unknown>:0 
01-08 07:59:03.590: E/RDIO(2933):   at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:59:03.590: E/RDIO(2933):   --- End of inner exception stack trace ---
01-08 07:59:03.590: E/RDIO(2933):   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:59:03.590: E/RDIO(2933):   --- End of inner exception stack trace ---
01-08 07:59:03.590: E/RDIO(2933):   at Hyena.Net.ManagedHttpWebRequest.Hyena.Net.IHttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
01-08 07:59:03.590: E/RDIO(2933):   at Hyena.Net.HttpClient+<PerformHttp>c__AnonStorey27.<>m__F (IAsyncResult result) [0x00000] in <filename unknown>:0 
01-08 07:59:03.770: I/RDIO(2933): PubSubSocket.BG: Socket receive thread started
01-08 07:59:03.820: I/RDIO(2906): RdioPlayerFrontendLocal: Setting CurrentTrack, key: t23546286:0:True track: t23546286
01-08 07:59:03.860: I/RDIO(2933): PubSubSocket.BG: Connected, notifying handlers
01-08 07:59:03.890: I/RDIO(2933): PubSubSocket.BG: Dequeing message
01-08 07:59:03.890: I/RDIO(2933): PubSubSocket.BG: Sending message: CONNECT s2452985_a30c3804ea0e8919601756182bf299c97c1756cc|{"player":{"name":"mobile_fde7477e-3224-4f17-a0d5-cd13918f7e27.BG","canRemote":true}}
01-08 07:59:03.890: I/RDIO(2933): PubSubSocket.BG: Sent message
01-08 07:59:03.910: I/RDIO(2933): Sequencer.BG: Shuffling indices with initial index=0
01-08 07:59:03.930: I/RDIO(2906): PlayerStateManager: Reloading state from JSON
01-08 07:59:03.980: I/RDIO(2933): PubSubSocket.BG: Received 1 bytes
01-08 07:59:03.980: I/RDIO(2933): PubSubSocket.BG: Received 47 bytes
01-08 07:59:03.980: I/RDIO(2933): PubSubSocket.BG: Assembled message, dispatching
01-08 07:59:03.990: I/RDIO(2933): PubSubConnection.BG: Received message: CONNECTED 5edad340-5993-11e2-9536-45419b351a26
01-08 07:59:03.990: I/RDIO(2933): PubSubConnection.BG: State change Connecting -> Connected
01-08 07:59:04.000: I/RDIO(2933): PubSubSocket.BG: Dequeing message
01-08 07:59:04.000: I/RDIO(2933): PubSubSocket.BG: Sending message: SUB s2452985/private
01-08 07:59:04.000: I/RDIO(2933): PubSubSocket.BG: Sent message
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Dequeing message
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Sending message: SUB s2452985/player
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Sent message
01-08 07:59:04.010: I/RDIO(2933): PubSubConnection.BG: Publishing event: PUB s2452985/private|{"event":"masterQuery"}
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Dequeing message
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Sending message: PUB s2452985/private|{"event":"masterQuery"}
01-08 07:59:04.010: I/RDIO(2933): PubSubSocket.BG: Sent message
01-08 07:59:04.170: I/RDIO(2933): Sequencer.BG: Sequence(): Attempting to sequence source: a2196371
01-08 07:59:04.250: I/RDIO(2906): PlayerStateManager: Reloading state from JSON
01-08 07:59:04.340: I/RDIO(2906): RdioPlayerFrontendLocal: Setting CurrentTrack, key: t23546286:0:True track: t23546286
01-08 07:59:04.880: I/RDIO(2906): RdioPlayerFrontendLocal: Setting CurrentTrack, key: t23546286:0:True track: t23546286
01-08 07:59:05.150: I/RDIO(2933): Sequencer.BG: Sequence(): Loaded source: a2196371
01-08 07:59:05.150: I/RDIO(2933): Sequencer.BG: Sequence(): Loaded tracks for source: a2196371
01-08 07:59:05.160: I/RDIO(2933): RdioPlayerBackend.BG: Sequencing of a2196371 completed, but we are no longer master.

**Comment by dasevilla** [comment]
Hi all, just to update this thread. I've been emailing with @milleph and another developer trying to get this issue figured out. Thanks for your patience.

**Comment by dasevilla** [comment]
A fix has been verified and is getting code reviewed before release.

**Comment by dasevilla** [comment]
The fix and been released in [Android SDK 1.1](http://www.rdio.com/media/static/developer/android/releases/rdio-android-1.1.tar.gz).
