### ISSUE TITLE
Web Playback API doesn't have methods

### ISSUE THREAD

**Issue by camwes** [rdio/api#166]
I noticed that the web player for my app had stopped working since the OAuth 2.0 migration and went to check out documentation only to find that the web playback API  (javascript) [example](https://github.com/rdio/hello-web-playback) is also broken. Inspecting the code I found:

``` js
Uncaught TypeError: Cannot read property 'rdio_play' of null
3hello.js:44 Uncaught TypeError: Cannot read property 'rdio_play' of null(anonymous function) @ hello.js:44d.event.handle @ jquery-1.5.1.min.js:16k.handle.m @ jquery-1.5.1.min.js:16
```

**Comment by dasevilla** [comment]
I believe this is the same issue as #168, are you still seeing this?

**Comment by camwes** [comment]
it is, I am still seeing the same error in both the example and in my application

**Comment by dasevilla** [comment]
The example app works for me when I run it locally. Is your application public so I can test?

**Comment by camwes** [comment]
how are you running it locally? I am using python SimpleHTTPServer to serve it on 8000, but the rdioswf object is still null [here](https://github.com/rdio/hello-web-playback/blob/master/js/hello.js#L44)

**Comment by dasevilla** [comment]
I'm doing the same: `python -m SimpleHTTPServer` and visiting http://localhost:8000/hello.html

Do you have any browser extensions such as ad blockers?  If so, try disabling them.

**Comment by camwes** [comment]
I disabled my ad blocker and am experiencing the same behavior

**Comment by camwes** [comment]
I am able to get the examples for the beta webapi to work, by adding thtp://localhost:8000 to my redirect urls, but that did not fix the current API, will close for now as my app is migrating away and I am sure this issue is more to do with the redirect_uri than the api itself, thanks for all of your help @dasevilla
