### ISSUE TITLE
Rdio SDK does not always return sufficient track metadata for a station, requires external API call

### ISSUE THREAD

**Issue by nickna** [rdio/api#172]
The Rdio SDK has the concept of player.currentSource, which contains a "tracks" array that should reflect the track metadata for the station. This metadata is often incomplete -- sometimes only a single track, often a small set of tracks that do not refresh as the station navigates forward. It is easy for the player.currentTrackIndex to be out of bounds on this array.

In order to get track metadata, Devin from Rdio has suggested making an external API call:

devin (Rdio eng.)
You can make an API call: get keys=t1234 http://www.rdio.com/developers/docs/web-service/methods/core/ref-get

Our team:
is that the intended way to get the track metadata? Is there a way to retrieve the additional info via the SDK?

Devin from Rdio:
Yes, that’s the recommended way to get metadata for any object

Our team:
that’s really the intended way to get metadata? get the track listing from the native iOS SDK, but then hit the web API for full metadata?
that sounds like it’s going to be really convoluted for us to implement
where sometimes we’re getting metadata from the SDK and sometimes we have to go out to the API

Devin from Rdio:
You’re right, that is bad. It should be available as part of rdio.player.currentSource. Until that’s fixed, the best way to get it to make the API call

This is ultimately a bug in the Rdio SDK.

**Comment by dasevilla** [comment]
Rather than digging around in `RDPlayer.currentSource` for the current track's metadata, you can now just find it in `RDPlayer.currentTrack`.

http://blog.rdio.com/developers/2015/10/ios-sdk-v400.html
