### ISSUE TITLE
iOS Framework armv7s support

### ISSUE THREAD

**Issue by mcernusca** [rdio/api#2]
Building project against iOS6 GM fails with:

ld: file is universal (2 slices) but does not contain a(n) armv7s slice: {path}/Rdio.framework/Rdio for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Assuming Rdio iOS Framework binary needs to be re-built to include armv7s architecture support.

**Comment by amsoell** [comment]
Question: What happens if one were to hardcode "armv6 armv7" into the architectures box? When I do that, my app compiles just fine, and runs in all my simulators properly. Is there a particular class of device that this won't run on?

**Comment by mcernusca** [comment]
@amsoell there is a thread over on the dev forums regarding this that might help: https://t.co/r9Eu3MuK
Looks like it should be ok for now.
If your deployment target is 4.3+ there is no reason to include armv6 support back in.

**Comment by dasevilla** [comment]
I'm working on a new build and should have it tested and ready this week.

**Comment by dasevilla** [comment]
Below you will find a link to a build of the Rdio iOS SDK. It was built using XCode 4.5 with a deployment target of 4.3 and 6.0 as the base SDK. The build should work on armv7, armv7s, and in the simulator.

I tested it quite a bit but I would appreciate feedback before I post to the developer site.

[Rdio iOS SDK for iOS6](https://www.dropbox.com/s/8i1u51rqozx30dy/rdio-ios.tar.gz)

**Comment by mcernusca** [comment]
@dasevilla thanks! Working great for me so far. Tested on iOS 5 and 6 across all armv7 devices. Hopefully someone can try the v7s slice on the real hardware tomorrow.

**Comment by dasevilla** [comment]
Has anyone had a chance to run the Rdio iOS SDK on an iPhone 5?

**Comment by mcernusca** [comment]
Yes - I got a beta out to a few iPhone 5 users and it has been running fine.

**Comment by dasevilla** [comment]
This has been pushed to production, you can now find it in the [normal location](http://developer.rdio.com/docs/read/iOS).
