### ISSUE TITLE
Add Rdio iOS SDK to CocoaPods

### ISSUE THREAD

**Issue by steveluscher** [rdio/api#24]
It would be lovely if developers could use the [CocoaPods](http://cocoapods.org) package manager to install the Rdio iOS SDK.

Adding a framework to the CocoaPods repository is reasonably simple once the SDK is made available through GitHub. See "[How to create a pod](http://cocoapods.org/#get_started)" on the CocoaPods website.

**Comment by wao813** [comment]
Anyone took a look at this?  Rdio is getting popular!  There's one for Spotify.

**Comment by dasevilla** [comment]
The amazing @ScottPetit created one: CocoaPods/Specs#4596
