### ISSUE TITLE
Bot that periodically stuffs new music I might like into a playlist of mine

### ISSUE THREAD

**Issue by iangilman** [rdio/api#28]
Based on my collection, or who knows!

**Comment by girasquid** [comment]
I'm working on something that does this - if you'd like to try an early version, send an email to recommendations-beta@beathound.com.

**Comment by iangilman** [comment]
Awesome; email sent. :-)

**Comment by dasevilla** [comment]
Checkout [Magic Playlist](http://www.magic-playlist.com/)

**Comment by iangilman** [comment]
Should we mark this as closed then? I figure the list of closed "project ideas" issues becomes a sort of directory of hacks.
