### ISSUE TITLE
mobile web audio

### ISSUE THREAD

**Issue by iangilman** [rdio/api#3]
We're working on a new version of the JavaScript API, and html5 audio playback on mobile is part of the plan. No ETA yet, but you can follow this bug for updates.

**Comment by iangilman** [comment]
We now have mobile web audio mostly working in a couple of browsers via the [new JavaScript API](https://groups.google.com/forum/?hl=en&fromgroups=#!topic/rdio-api/_UlW2Oc6Dvc). It works in iOS 6 Safari and Android Opera, but things run aground if you let the phone fall asleep. At any rate, it's working well enough to develop against; if you're interested, sign up for the beta.

**Comment by iangilman** [comment]
I've just landed a fix to the iOS 6 Safari playback: audio can still get interrupted, but it can now be resumed.

**Comment by iangilman** [comment]
I have word that playback works on Windows Phone 8 and 7.

**Comment by iangilman** [comment]
And now with a recent iOS update (as of 6.1), web playback on iOS Safari no longer works with the JS API. It looks like they went back to the "requires user action" restriction that they had in iOS 5. I don't know that we'll be able to work around this.

**Comment by iangilman** [comment]
Ok, we are in fact working around it, with a dialog box that comes up when needed. This has been deployed and verified to work on iOS 5 & 6. The fix for Android Chrome should be landing today.

**Comment by iangilman** [comment]
Ok, I'm sure we'll make improvements in this area, but I'm going to close this now, as we have basic functionality working.

**Comment by bsiddiqui** [comment]
Is this actually working? The rdio webplayback API works for me on the web but not mobile web...? Is this bc I'm using the rdio jquery lib?

**Comment by iangilman** [comment]
Yes, this is true only of the new JavaScript API that's still in beta. The Web Playback API you're using does not work on mobile. Send email to developersupport@rd.io to request access to the beta API.
