### ISSUE TITLE
Login view layout problems on Landscape iPad

### ISSUE THREAD

**Issue by xinsight** [rdio/api#31]
The rdio login view controller has some layout problems on a landscape iPad.

The bars do not stretch the full width of the screen – only 748px wide, not 1024. (Oddly the bars are actually wider when displayed in portrait as they are the full screen width: 768px)

Also, the close button is far too small to tap. It looks like it is only 14x14! (44 is recommended.)

```
<UIButton: 0x20a970d0; frame = (743 10; 14 14); opaque = NO; layer = <CALayer: 0x20a97190>>
```

![rdio-ipad-login](https://f.cloud.github.com/assets/465971/13219/c62e88ec-45ee-11e2-9391-e1c61fae48a9.PNG)

**Comment by rknLA** [comment]
Just wanted to post a quick update on this bug.  It's still on our radar, and we've been having internal discussions about the best approach to fixing the problem.

I'm going to begin working on a short-term fix on Monday to stretch the bars appropriately and increase the button size.  We have some longer term plans for changes as well, and they're going to be great, but I don't think they're going to be ready soon enough to be a timely fix to this issue.

**Comment by dasevilla** [comment]
The short-term fix has been released. The sign in page now expands to fill the screen.

The size of the close button still remains an issue, please follow #39 for further updates.
