### ISSUE TITLE
Android API doesn't work with new Rdio Android Application (STILL)

### ISSUE THREAD

**Issue by milleph** [rdio/api#35]
Although the previous post on this issue resulted in a new release, a supposed fix and a closing of the issue, the issue is not resolved. Don't take this the wrong way but before I waste any more time can you tell me if the lack of responsiveness on this bug is a priority issue, or if native third-party Android app support is being dropped (slowly), or both, or neither. Frankly, even an 'hello' at this stage would be viewed as progress.

From over a month ago (posted by mlegris)

You updated your application two days ago. Ever since, your Android API doesn't work well at all when the Application is present. If you uninstall it all works fine. Otherwise, all hell breaks loose. Nothing works, no authentication, api call, playback. Nada.

**Comment by tberman** [comment]
I am closing this because the original issue tracks it better, I have also pinged the people involved with the original issue to get them to look at it again.
