### ISSUE TITLE
Historical heavy rotation

### ISSUE THREAD

**Issue by iangilman** [rdio/api#36]
Inspired by: https://twitter.com/jessicahische/status/287364419678253057

At least for people who have been scrobbling their plays to last.fm, you could use http://www.last.fm/api/show/user.getWeeklyAlbumChart to grab your heavy rotation from any time period in the past.

**Comment by rknLA** [comment]
cc @rferguson

**Comment by hotmeteor** [comment]
I've got a good start on it here: http://resp.in/history/
Next will be working on a way to import stuff in Rdio.

**Comment by hotmeteor** [comment]
Update: you can now click "Find on Rdio" and get album art and link to the item on Rdio. This should be enough to help folks build playlists, etc.

**Comment by iangilman** [comment]
This is awesome! 

So, should we close this issue? I think this is the first project idea that's been done, so I'm not sure what the procedure should be...

**Comment by hotmeteor** [comment]
It's about as far as I plan to take it without further suggestions, so... yes, closed.

**Comment by iangilman** [comment]
Fair enough! Closing.

If people do have suggestions, where should they send them?

**Comment by hotmeteor** [comment]
Good question. I guess they can tweet me or Resp.in at @hotmeteor / @resp_in ?
