### ISSUE TITLE
Close button for sign in page is too small

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#39]
The close button is far too small to tap. It looks like it is only 14x14! (44 is recommended.)

```
<UIButton: 0x20a970d0; frame = (743 10; 14 14); opaque = NO; layer = <CALayer: 0x20a97190>>
```

This is task is carries over from #31.

**Comment by rknLA** [comment]
Closing this as `wontfix`, since this screen will be gone in the next release of the SDK.
