### ISSUE TITLE
500 Error when requesting oauth token

### ISSUE THREAD

**Issue by gotosleep** [rdio/api#4]
When requesting an oauth token, after clicking "Allow >", I am getting a 500 error with the message:

```
Server Error
Sorry, something bad happened, an error has been logged and will be fixed as soon as possible.
```

It used to work; I'm not sure when it broke.

My app is a Chrome extension called "Awesome List for Rdio". Here is a link to the app: https://chrome.google.com/webstore/detail/abgahpfoemegcefacbimgdjgefgmppnl

Here is an example of the callback url: 

```
chrome-extension://nicoghogocnbpajalddmbabodkjobhmn/background.html?chromeexoauthcallback=true
```

Any help would be greatly appreciated.

**Comment by gotosleep** [comment]
It looks like you guys have fixed the issue. I am no longer experiencing this problem. Thanks!

**Comment by dasevilla** [comment]
Yep! There was a bug that we fixed, thanks for closing the issue.
