### ISSUE TITLE
Feature Request: Allow seeing if an album or track is flagged to sync to mobile

### ISSUE THREAD

**Issue by sclm** [rdio/api#42]
Currently through the API it is possible to mark a track or playlist for syncing, but it is not possible to know if something is already marked for it.

This would be helpful as it would allow for more accurate UIs when going to set that and, in particular, reduce unneeded calls to the API to set tracks and playlists that are already marked for syncing.

**Comment by rknLA** [comment]
We have released a new method, [`getOfflineTracks`](http://developer.rdio.com/docs/read/rest/Methods#getOfflineTracks) that should help you in your hacking.
