### ISSUE TITLE
Applescript bugs/issues

### ISSUE THREAD

**Issue by connor** [rdio/api#47]
Hey there,

I'm experiencing the following issues with the AppleScript dictionary:
- `playerPosition` is incorrect & buggy
- repeat is not available
- would appreciate setter method on shuffle
- artwork is also buggy

Happy to expand on these, just not able to right now. Thought I'd report these, though. Thank you!

**Comment by rknLA** [comment]
Hi Connor,

Thanks for the report.  If you could elaborate on the `playerPosition` and artwork bugginess, it'd make it easier for us to find the source of the problem.  Steps to reproduce would also be great.

Thanks!
Kevin

**Comment by dasevilla** [comment]
You can enable shuffle with:

```
tell application "Rdio" to set shuffle to true
```

I've filed the other issues in our internal tracker

**Comment by neersighted** [comment]
I do believe that `playerPosistion` now uses percentages (undocumented change?).

**Comment by dasevilla** [comment]
@neersighted thanks for the update, it does seem to be percentages. I've updated the internal task with more information. AppleScript bug fixes aren't a priority right now, so I don't know when the team will be able to fix this.

**Comment by connor** [comment]
Excellent. Thank you @neersighted!

**Comment by dasevilla** [comment]
As of v2.30 you can set the repeat state:

```
tell application "Rdio"
    set repeat state to STATE
end tell
```

Where `STATE` can be: `one`, `all`, `none`.

We've also fixed the position to use seconds instead of a percentage.

This now seeks to the 30-second mark:

```
tell application "Rdio"
    set player position to 30
end tell
```

This returns the current position in seconds:

```
tell application "Rdio"
    player position
end tell
```
