### ISSUE TITLE
comma separated extras throwing "401 Invalid Signature"

### ISSUE THREAD

**Issue by samullen** [rdio/api#49]
Hey, guys, just ran across something on a project I'm building. We're seeing errors from the "get" method when passing a User ID as the key and a list of "extras" values. In our case it's "lastSongPlayed,lastSongPlayTime". The result is a "401 Invalid Signature".

Everything works fine if I pass "lastSongPlayed" or "lastSongPlayTime", but combined results in the error.

**Comment by dasevilla** [comment]
The issue should be resolved now, let me know if you're still experiencing issues. I'll be posting a recap once the dust settles.

**Comment by dasevilla** [comment]
Here the [recap of this issue](https://groups.google.com/d/msg/rdio-api/vJl0Bod31Dw/Gyh8nSoiCxEJ)
