### ISSUE TITLE
Android SDK connection reset issue on Jelly Bean

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#5]
The Android SDK is suffering from repeated connection reset exceptions before playback eventually starts. This only occurs when running on Jelly Bean.

[Original report](https://groups.google.com/d/msg/rdio-api/-/enmVMNGus2gJ):

> Same code works fine on ICS but on the Nexus 7 running Jellybean
> 
> ```
> _mp = rdio.getPlayerForTrack(id, null, true);
> ```
> 
> then the following throws exceptions..
> 
> ```
> _mp.prepare();
> ```
> 
> java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
> 
> Track eventually starts playing after 20 seconds or so.

**Comment by milleph** [comment]
Not sure what the status of this is but......

http://stackoverflow.com/questions/11606146/android-media-player-how-to-disable-range-request-broken-audio-streaming-on

**Comment by dasevilla** [comment]
Haven't started work on a fix yet, thanks for the link!

**Comment by mlegris** [comment]
Hi. Do you guys have a timeframe for a fix to this? It works fine when you load 30 secs excerpts, but it doesn't work at all on full tracks. This breaks our app pretty badly on Jelly Bean. Is it possible to get a sense of how long it might take to find a fix? All my devices (ASUS Transformer Prime, Galaxy Nexus and the Nexus 7) are now updated to Jelly Bean.

On the Galaxy Nexus the app just closes for no reason at all after it fails. Some android bug I guess. The others it just keeps failing and failing and failing... 

Thanks!

**Comment by mlegris** [comment]
Also I tried loading the Rdio API from a Service that runs in another process than my app. I get the same problem. :(

**Comment by milleph** [comment]
I never thought to check that! Can confirm that if the Rdio app is not installed the 30s samples play fine..... I love progress - thanks mlegris!

**Comment by milleph** [comment]
Alas, Android 4.1.2 changes nothing

**Comment by mlegris** [comment]
they need to change their server's responses to those requests. Why is it
that the Rdio application works ok, but not the API? I can't understand
that. Surely their app uses the same Android object to play music. That
means that the API consumes music from another server than the main Rdio
server.

On Fri, Oct 12, 2012 at 7:33 PM, milleph notifications@github.com wrote:

> Alas, Android 4.1.2 changes nothing
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rdio/api/issues/5#issuecomment-9397639.

## 

Martin Legris
The Seed & The Gardener -- TasteFilter Inc

t/f: +1.514.448.0362
c: +1.514.574.3982

skype: martin.legris

**Comment by milleph** [comment]
Any update on this?

**Comment by dasevilla** [comment]
No progress yet, but this is still on my radar. The issue is that Jelly Bean seems to give up on the stream faster than previous releases.

The Rdio mobile apps share a library based on Mono, while the Android SDK is Java.

**Comment by milleph** [comment]
so how come your app works fine?

**Comment by rknLA** [comment]
I'm pretty sure [this version of the SDK](http://db.tt/KV6SfM3e) fixes the issue.  Wanna give it a spin and let us know?

As @dasevilla mentioned, our apps use a slightly different backend than the SDK.  We did run into this bug on the Rdio mobile apps, but porting the fix was somewhat involved.

**Comment by mlegris** [comment]
works for me! woohoo! and I pointed out your backend must have been
different following some pretty serious deductions.

On Thu, Nov 8, 2012 at 5:03 PM, kevin nelson notifications@github.comwrote:

> I'm pretty sure this version of the SDK http://db.tt/KV6SfM3e fixes the
> issue. Wanna give it a spin and let us know?
> 
> As @dasevilla https://github.com/dasevilla mentioned, our apps use a
> slightly different backend than the SDK. We did run into this bug on the
> Rdio mobile apps, but porting the fix was somewhat involved.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rdio/api/issues/5#issuecomment-10206988.

## 

Martin Legris
The Seed & The Gardener -- TasteFilter Inc

t/f: +1.514.448.0362
c: +1.514.574.3982

skype: martin.legris

**Comment by rknLA** [comment]
Excellent.  We'll put these fixes through code review and into a proper release shortly.  Thanks!
