### ISSUE TITLE
Android: Cleanup method doesn't work

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#54]
The `cleanup` method will put the Android SDK into an illegal state.

**Comment by ghost** [comment]
Any update on or estimate on when this issue might be fixed?

**Comment by ghost** [comment]
Checking in to see if there are any updates on this issue which I am currently blocked with. 

Thanks

**Comment by dasevilla** [comment]
Fixed in v2.0.0, checkout the [release notes](http://on.rdio.com/1g5iERX).
