### ISSUE TITLE
iOS SDK / login with Facebook

### ISSUE THREAD

**Issue by romyilano** [rdio/api#55]
Does the iOS SDK include easy ways for the users to sign in with Facebook? 
- using the Facebook oauth or
- using the facebook sign in that comes with iOS 6

**Comment by dasevilla** [comment]
The iOS SDK does not yet handle Facebook authentication. We will be adding support to the iOS and Android SDKs, I don't yet have an ETA.

**Comment by rknLA** [comment]
This has been addressed for iOS in today's [version 1.3 release](https://groups.google.com/forum/#!topic/rdio-api/6yUR659Hkyg)
