### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by 1010010010** [rdio/api#6]
this doesnt really absolutely fit into here but here are the people around that know how to do it:
anyone want to create a chrome extension to skip to next track, so i dont need to change to rdio tab?

**Comment by iangilman** [comment]
Actually, I think it's a great idea to post project ideas here! I've added a label just for that. 

Just to clarify on this project: how does this differ from the desktop apps that support the same behavior? If you're on Linux, have you tried the Unity extension?

**Comment by 1010010010** [comment]
i know your desktop app on windows, but anyway i would prefer a chrome extension where i can skip to the next track in the right corner of chrome, between the favorite star and options button.
Most people are using a lot of time in their browser, so why should they have to change to another program if they just want to skip a track.

Your Desktop app is nice but i think it s not really needed because rdio in browser is already great.
(that s a compliment ... not a reproval). Actually i even ordered a creditcard to be able to use your service ...

And please promise to stay that way you are, not including facebookbuttons on every page! your clean and great webplayer makes the difference for me between your service and deezer or simfy.

Finally most time i am using Fedora with Gnome, so i can t use the desktop player at all (but as stated before i dont really miss it).

And last but not list, don t sell your soul to microsoft. I read a rumor about that today ...

Ok sorry, i went a little bit of, but i wanted to use this chance to talk to a rdio developer ;D

**Comment by jldupont** [comment]
This issue is related to issue #1 ( https://github.com/rdio/api/issues/1 ) I believe: It will be much easier to build a Chrome extension once we have the official API.

**Comment by iangilman** [comment]
@Chr1stopher: I'm glad you like our approach! Focusing on the web tech gives us the most flexibility. And yes, as @jldupont points out, once we have the remoting capability in the new JS API, this should be a piece of cake.

**Comment by connor** [comment]
Here's one I worked on a little while ago that does this kind of thing — http://cnnr.me/blog/2012/01/01/keyboard-shortcuts-on-rdios-web-app/.

Unrelated: apologies for the mostly unstyled blog. Haven't gotten around to making it pretty yet.

**Comment by iangilman** [comment]
Very cool! Now someone just needs to package it up for easy consumption. :-)

**Comment by jldupont** [comment]
What we really need is http://www.w3.org/TR/webmessaging/ for rdio.com
That would make for an easy Chrome extension (or Firefox etc.).

(Updated link above)

**Comment by iangilman** [comment]
I should mention that we do now have remoting capability in the JS API. I believe we'll focus on that, rather than adding direct support for web messaging.
