### ISSUE TITLE
API does not return bigIcon for tracks through “getTracksForAlbumInCollection” method

### ISSUE THREAD

**Issue by steveluscher** [rdio/api#62]
I've tried `bigIcon`, `Track.bigIcon`, `Album.bigIcon`, and `CollectionAlbum.bigIcon`. What's the correct incantation to get large album art using the `getTracksForAlbumInCollection` method?

http://rdioconsole.appspot.com/#album%3Da1801634%26user%3Ds373816%26extras%3DbigIcon%26method%3DgetTracksForAlbumInCollection

**Comment by JustinTulloss** [comment]
There's currently a bug in the API (we no longer use that API internally). We'll fix it soon.

**Comment by djensenius** [comment]
Any updates or release timeline for this bug?

**Comment by dasevilla** [comment]
Fix has been fixed. This method now respects the `extras` parameter.

**Comment by steveluscher** [comment]
I wish you could :thumbsup: things on GitHub.
