### ISSUE TITLE
iOS SDK Can programmatically pause between queued tracks, but not before the first one starts

### ISSUE THREAD

**Issue by steveluscher** [rdio/api#64]
Since the Rdio iOS SDK doesn't let us programmatically preload tracks, I've been trying to implement preloading by calling for tracks to be played, but pausing them just before they start.

This seems to work if the player is _already playing_. If I play three sources, then try to pause the player between the first and second track: no problem.

If, however, I play three sources and then try to pause the player before the first one begins to play, the RDPlayer goes insane. It fires calls to `rdioPlayerChangedFromState:toState:` in an infinite loop, where the `fromState` and `state` are both `RDPlayerStatePlaying`.

Here's a branch of the Hello app demonstrating the working "pause between tracks" case: https://github.com/steveluscher/hello-ios-playback/compare/pause_between

Here's a branch of the Hello app demonstrating the broken "pause before the first track" case: https://github.com/steveluscher/hello-ios-playback/compare/initially_paused

**Comment by steveluscher** [comment]
It seems that if you dare to call `[player togglePause]` from _inside_ `rdioPlayerChangedFromState:toState:` while the Rdio SDK is in some particular state (buffering?), the `togglePause` method recurses into `rdioPlayerChangedFromState:toState:` to let you know that the state changed from `RDPlayerStatePlaying` to `RDPlayerStatePlaying`. Wait… what?

**Comment by rknLA** [comment]
Interesting.  These are all valid points that we're taking note of.  We've been a bit quiet on the iOS SDK front lately, as we've been working hard to improve it.  Some very welcome changes are coming soon.

**Comment by steveluscher** [comment]
Thanks Kevin. We're pumped to hear that. We'll keep feeding you bug reports as we discover them.

**Comment by dasevilla** [comment]
The latest iOS SDK contains many fixes to streaming. If you can still reproduce this issue, please reopen.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
