### ISSUE TITLE
[iOS] Improve the reliability of seekToPosition:

### ISSUE THREAD

**Issue by steveluscher** [rdio/api#65]
I can reproduce the problem that [these folks](https://groups.google.com/forum/?fromgroups=#!topic/rdio-api/Aor4ghrosqI) are having.

It's reasonable to expect that this would work:

```
[player playSource:@"t17891017"];
[player seekToPosition:10];
```

Of course, since the audio stream has not started yet it throws:

```
AudioStreamer seekToPosition called with no audio queue!
```

The seek function should understand what song it's operating on, and defer execution until the stream is ready. That, or we should have a `playSource:startingAtPosition:` method.

**Comment by dasevilla** [comment]
This is fixed in v2.0.0

http://blog.rdio.com/developers/2014/05/ios-sdk-20-migration-guide.html
