### ISSUE TITLE
Crash in AudioStreamer.m

### ISSUE THREAD

**Issue by JohnGluszak** [rdio/api#77]
I was playing music from Rdio and I got this crash:

Fatal Exception NSUnknownKeyException
[<NSConcreteMutableData 0x2018d060> valueForUndefinedKey:]: this class is not key value coding-compliant for the key duration.

Happened in:

AudioStreamer.m line 732
-[AudioStreamer loadedPlaybackInfo:]

**Comment by rknLA** [comment]
Very odd.  Can you provide the calls that you made to RDPlayer that generated this error?

It will probably also be helpful to know the track key that the AudioStreamer failed on.  Is that available in your logs?

**Comment by JohnGluszak** [comment]
Thanks for the fast reply Kevin!

We are in the process of changing our logging system to Crashlytics,

We

**Comment by rknLA** [comment]
Based on email conversations, this crash appears to be related to the general GCD issue https://github.com/rdio/api/issues/83
