### ISSUE TITLE
Crash in OARequestParameter.m

### ISSUE THREAD

**Issue by JohnGluszak** [rdio/api#78]
I was playing music from Rdio (my app was in the background state), and I got this crash:

Fatal Exception NSInvalidArgumentException
-[NSConcreteData encodedURLParameterString]: unrecognized selector sent to instance 0x1f2634f0

Happened in:

OARequestParameter.m line 54
-[RD_OARequestParameter URLEncodedValue]

**Comment by rknLA** [comment]
I'm assuming this crash occurred entirely separately from #77?

Can you provide the tracks that you had queued up?

**Comment by rknLA** [comment]
Based on email conversations, this crash appears to be related to the general GCD issue https://github.com/rdio/api/issues/83
