### ISSUE TITLE
Crash in RDPlayer.m

### ISSUE THREAD

**Issue by JohnGluszak** [rdio/api#79]
Crashed at:

RDPlayer.m line 741
-[RDPlayer queueSourcesForRequest:withData:andSourceKeys:]

With error:

-[NSConcreteMutableData objectForKey:]: unrecognized selector sent to instance

This happened when streaming track with key: t31341699

**Comment by rknLA** [comment]
Based on email conversations, it seems this issue is related to the GCD issue https://github.com/rdio/api/issues/83
