### ISSUE TITLE
Setting player position via AppleScript changed

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#80]
It seems that it sets it as a percent, previously it was setting it to the exact second.

```
tell application "Rdio"
    set player position to 30
end tell
```

**Comment by din** [comment]
This is still an issue. `playerPosition` variable still behaves really bizarre. Can you tell me if there is a fix or anything for that behaviour?

**Comment by dasevilla** [comment]
As of v2.30 we've fixed the position to use seconds instead of a percentage.

This now seeks to the 30-second mark:

```
tell application "Rdio"
    set player position to 30
end tell
```

This returns the current position in seconds:

```
tell application "Rdio"
    player position
end tell
```
