### ISSUE TITLE
Rdio JS Queues break api

### ISSUE THREAD

**Issue by cujomalainey** [rdio/api#84]
The code below seems to cause the api to fail, i have also attempted another version of this code without jquery controlling there API but both produced similar results. The JSON is below that is returned from my site. The console successfully logs the tracks being cued. But the play function will not run, also on my other set of code i had callbacks setup, and they also wouldn't run until I ran the function that queued the tracks a second time. Also using the link with id "play" would trigger the track to play. About 1/5 times it would actually play. Any ideas why queues are causing these problems? 

```
var duration = 1; // track the duration of the currently playing track
$(document).ready(function() {
    $('#api').bind('ready.rdio', function() {
        $.getJSON('MYSITE.COM', function(data) {
            str = "";
            results = data;
            for(var row in results) {
                str += "<li>" + results[row].name; + "</li>";
                $('#api').rdio().queue(results[row].key);
                console.log(results[row].key);
            }
        });
        $('#queue').text = str;
        $(this).rdio().play();
    });
    $('#api').bind('playingTrackChanged.rdio', function(e, playingTrack, sourcePosition) {
        if (playingTrack) {
            duration = playingTrack.duration;
            $('#art').attr('src', playingTrack.icon);
            $('#track').text(playingTrack.name);
            $('#album').text(playingTrack.album);
            $('#artist').text(playingTrack.artist);
        }
    });
    $('#api').bind('positionChanged.rdio', function(e, position) {
        $('#position').css('width', Math.floor(100*position/duration)+'%');
    });
    $('#api').bind('playStateChanged.rdio', function(e, playState) {
        if (playState == 0) { // paused
            $('#play').show();
            $('#pause').hide();
        } else {
            $('#play').hide();
            $('#pause').show();
        }
    });
    // this is a valid playback token for localhost.
    // but you should go get your own for your own domain.
    $('#api').rdio(document.getElementById('token').value);

    $('#previous').click(function() { $('#api').rdio().previous(); });
    $('#play').click(function() { $('#api').rdio().play(); });
    $('#pause').click(function() { $('#api').rdio().pause(); });
    $('#next').click(function() { $('#api').rdio().next(); });
});
```

JSON

```
[{"key":"t16494017","name":"Human","icon_url":"http:\/\/cdn3.rd.io\/album\/c\/d\/6\/00000000001676dc\/1\/square-200.jpg","artist":"Manafest","album":"Fighter","is_explicit":"0"},{"key":"t11604279","name":"Afterlife","icon_url":"http:\/\/rdio-c.cdn3.rdio.com\/album\/3\/1\/0\/00000000000f4013\/square-200.jpg","artist":"Switchfoot","album":"Vice Verses (Deluxe)","is_explicit":"0"}]
```

**Comment by iangilman** [comment]
I can't speak to this issue, as I'm not familiar with the Playback API, but you might try the new JavaScript API we've put together. It's still in beta but pretty robust, and handles playback and queuing, as well as a number of other features. If you're interested, let us know at developersupport@rd.io.

**Comment by cujomalainey** [comment]
Thank you @iangilman I'm going to take one more stab at this project with this API, if i'm unsuccessful i will be looking for the beta

**Comment by cujomalainey** [comment]
For those who manage the code, the issue i have discovered is that if you queue a song before the callback is complete from the song before it then it breaks things. Or if you queue songs while the api is switching states bad things happen

**Comment by iangilman** [comment]
Thanks for hunting this down!
