### ISSUE TITLE
Track events for a person you're not following

### ISSUE THREAD

**Issue by elskwid** [rdio/api#88]
The JS API expects us to `trackField("lastSongPlayed")` on a following person. 

I would like to get a similar person object from the JS API for a person that isn't in my following list. Then I could `trackPresence` and `trackFields` for as long as I need.

**Comment by iangilman** [comment]
Great idea... I shall look into it.

**Comment by iangilman** [comment]
Ok, this is in now. The call is `R.getTrackableObject()`. I'm updating the docs, but here's an example:

```
R.getTrackableObject('s1', function(person) {
  person.trackField('lastSongPlayed');
});
```
