### ISSUE TITLE
Last song play time in JS API

### ISSUE THREAD

**Issue by elskwid** [rdio/api#89]
We can ask for the `lastSongPlayed` but we don't get any time information. It would be great to get the `lastSongPlayTime` information along with it. The best bet currently is to issue `R.request()` with "findUser" and ask for the play time in the `extras`.

**Comment by iangilman** [comment]
I'll see if we have access to this information at the JS level.

**Comment by iangilman** [comment]
This now works! Example code:

```
person.on('change:lastSongPlayTime', function(time) {
  console.log(person.get('lastSongPlayTime'));
});

person.trackField('lastSongPlayTime');
```

**Comment by elskwid** [comment]
This rules so hard!

:sparkles: @iangilman :sparkles:

**Comment by phlipper** [comment]
:heart_decoration: :headphones:
