### ISSUE TITLE
Crash after resuming play from phone call interruption

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#9]
[Original thread](https://groups.google.com/d/msg/rdio-api/-/26IwvqW1iAwJ):

> I'm getting a crash in the Rdio iOS api when a phone call ends.  It looks like the handler runs when the call finishes, but RDPlayer is deallocated for some reason.  Any ideas?
> 
> 2012-10-22 17:52:15.235 [3277:907] **\* -[RDPlayer handleInterruption:]: message sent to deallocated instance 0x1e810700
> 2012-10-22 17:52:25.889[3277:907] **\* -[RDPlayer class]: message sent to deallocated instance 0x1e810700
> 
> AudioToolbox`mshMIGPerform:
> AudioToolbox`_XAudioSessionInterruptionListenerMessage:
> AudioToolbox`ASCallbackReceiver_AudioSessionInterruptionListenerMessage:
> AudioSessionClient::CallInterruptionListener(unsigned long)
> 
> `audioSessionInterruptionListener at RDPlayer.m:40:
> 0xbd35c:  push   {r7, lr}
> 0xbd35e:  mov    r2, r1
> 0xbd360:  movw   r1, #27914
> 0xbd364:  movt   r1, #64
> 0xbd368:  mov    r7, sp
> 0xbd36a:  add    r1, pc
> 0xbd36c:  ldr    r1, [r1]
> 0xbd36e:  blx    0x3cb0f8                  ; symbol stub for: objc_msgSend
> 0xbd372:  pop    {r7, pc}

**Comment by rknLA** [comment]
@bendytree Any chance you have an example project that exhibits this bug?

I've tried reproducing this issue using the Rdio Quiz sample App and have not been able to.

Thanks!
Kevin

**Comment by jogu** [comment]
This similar crash report in audiostream may be useful as it has a solution that may be relevant:

https://github.com/mattgallagher/AudioStreamer/issues/6

**Comment by dasevilla** [comment]
The latest iOS SDK contains many fixes to streaming. If you can still reproduce this issue, please reopen.

http://blog.rdio.com/developers/2015/06/ios-sdk-v302.html
