### ISSUE TITLE
rdioIsPlayingElsewhere delegate method not called (iOS SDK)

### ISSUE THREAD

**Issue by hunterbridges** [rdio/api#94]
The `rdioIsPlayingElsewhere` delegate method (on RDPlayerDelegate) is not called when a user starts playing a track on their Rdio account on another device

**Comment by rknLA** [comment]
I'm not able to reproduce this.

It's worth noting that `rdioIsPlayingElsewhere` is not called in real-time when playback begins on another device, but at the beginning of the next track in the queue.

If you're seeing behavior that differs from what I just described, please re-open the issue and provide more details, preferably including steps to reproduce.
