### ISSUE TITLE
Crash on iOS when playing a song with playSource:

### ISSUE THREAD

**Issue by djfitz** [rdio/api#95]
I'm currently using the iOS Rdio SDK 1.3.2.

I'm attempting to play a track using -[RdPlayer playSource:]. However I get a crash:

Name = NSRangeException
Reason = **\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
User Info = (null)

If I play the track using -[RdPlayer queueSource:] instead, everything plays fine. Unfortunately, this will play the track, then repeat by default. This means it plays twice.

**Comment by rknLA** [comment]
Thanks for reporting!

As mentioned in the [email thread](https://groups.google.com/forum/#!topic/rdio-api/2wpml3Z5BN8), this bug has been fixed in v1.3.3 of the SDK.
