### ISSUE TITLE
inclusion of NSData+Base64 causes linking errors

### ISSUE THREAD

**Issue by colinta** [rdio/api#96]
I'm using this framework alongside the TWReverseAuth cocoapod, and there is a duplicate symbol error because NSData+Base64 is included.

You could namespace NSData+Base64; modify the source so that the functions, classes, and methods are uniquely named.

Better yet, release a CocoaPod already, and list Base64 as a dependency https://github.com/CocoaPods/Specs/blob/master/NSData+Base64/1.0.0/NSData+Base64.podspec

**Comment by ScottPetit** [comment]
Colinta,

Listing Bas64 as a dependency would only cause the linker error to happen every time.  As cocoapods would bring in that dependency if it's not already included by any other pods but has no knowledge of what's actually in the .framework.  The better solution would be for any third party dependencies to be properly namespaced IMO.

**Comment by rknLA** [comment]
This is covered in the [Troubleshooting](http://www.rdio.com/developers/docs/libraries/ios/ref-troubleshooting) section of our iOS Docs.

If and when we do release a CocoaPod, we'll be taking this into consideration.
