### ISSUE TITLE
iOS SDK is not 64 bit limiting any apps to 32 bit

### ISSUE THREAD

**Issue by DavidBrunow** [rdio/api#98]
Here is the error log from the compiler when I try to compile for 64 bit:

ld: warning: ignoring file /Users/davidhbrunow/Documents/Development/Rdio Alarm Clock/Rdio Alarm Clock/External Frameworks/Rdio.framework/Rdio, missing required architecture arm64 in file /Users/davidhbrunow/Documents/Development/Rdio Alarm Clock/Rdio Alarm Clock/External Frameworks/Rdio.framework/Rdio (3 slices)
ld: warning: ignoring file /Users/davidhbrunow/Documents/Development/Rdio Alarm Clock/Rdio Alarm Clock/Classes/TestFlightSDK1/libTestFlight.a, missing required architecture arm64 in file /Users/davidhbrunow/Documents/Development/Rdio Alarm Clock/Rdio Alarm Clock/Classes/TestFlightSDK1/libTestFlight.a (4 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Rdio", referenced from:
      objc-class-ref in AppDelegate.o
     (maybe you meant: _OBJC_CLASS_$_RdioUser)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rknLA** [comment]
Thanks for the report.  We're working on rolling 64-bit support into a release soon.

**Comment by fastmiso** [comment]
Hello,

I'm trying to link to the Rdio framework for 64-bit (arm64, x86_64), too, but no luck. Using Rdio iOS Framework (version 1.3.6, released 13 February, 2014). Confirmed with lipo -iinfo that 64-bit symbols are lacking. 

Any suggestions?

Thanks!

**Comment by DavidBrunow** [comment]
Nope, I've got nothing. I'm still compiling for 32 bit and waiting for the API team to do their thing.

## 

David

**Comment by rknLA** [comment]
We have 64-bit support slated for our next release, which will also include some other breaking changes and new features.

**Comment by fastmiso** [comment]
Awesome! Thanks!

**Comment by runmad** [comment]
@rknLA Thanks... ETA?

**Comment by rknLA** [comment]
I don't have anything more specific than "soon", but, soon!

**Comment by dasevilla** [comment]
This is fixed in v2.0.0

http://blog.rdio.com/developers/2014/05/ios-sdk-20-migration-guide.html
